var krpanoplugin=function(){function Y(e){a.handcursor=!0}function Z(e){a.handcursor=!1}function Da(e){var d=-1,f;e=a.getmouse().y;for(f=0;f<q&&0>d;){if(e>A[f]&&e<A[f+1]){d=x*q+f;break}f++}d>D.length-1||(e=getSceneName(D[d]).split(";"),e[0]=e[0].trim(),e[1]=e[1].trim(),e[0]!=G.xml.scene?G.call('loadscene("'+e[0]+'");looktohotspot("'+e[1]+'");'):(ka(),G.call('looktohotspot("'+e[1]+'");')))}function ka(){if(0!=I)aa(),I=0;else{for(var e=0;e<z;e++)for(var d=e*q*h,f=0;f<q;f++)for(var k=f*h,n=0;n<h;n++){var l=
d+k+n;t[l].setAttribute("visibility","hidden");m[l].setAttribute("visibility","hidden")}1<z&&(u.setAttribute("visibility","hidden"),r.setAttribute("visibility","hidden"));K.setAttribute("visibility","hidden");null!=B&&B.setAttribute("visibility","hidden");for(f=0;f<h;f++)H[f].setAttribute("visibility","hidden"),v[f].setAttribute("visibility","hidden");p.setAttribute("fill-opacity",U);p.firstChild.nodeValue="ALARMS="+la;a.registercontentsize(oa,20);I=1}}function va(a){x--;0==x?u.setAttribute("visibility",
"hidden"):(da=String("<"+x),u.firstChild.nodeValue=da);r.setAttribute("visibility","visible");ea=String(x+2+">");r.firstChild.nodeValue=ea;aa()}function wa(a){x++;x==z-1?r.setAttribute("visibility","hidden"):(ea=String(x+2+">"),r.firstChild.nodeValue=ea);u.setAttribute("visibility","visible");da="<"+x;u.firstChild.nodeValue=da;aa()}function aa(){for(var e=0;e<z;e++)for(var d=e*q*h,f=0;f<q;f++)for(var k=f*h,n=0;n<h;n++){var l=d+k+n;e!=x?(m[l].setAttribute("visibility","hidden"),t[l].setAttribute("visibility",
"hidden")):(t[l].setAttribute("visibility","visible"),m[l].setAttribute("visibility","visible"))}0<x&&u.setAttribute("visibility","visible");x<z-1&&r.setAttribute("visibility","visible");K.setAttribute("visibility","visible");null!=B&&B.setAttribute("visibility","visible");for(f=0;f<h;f++)H[f].setAttribute("visibility","visible"),v[f].setAttribute("visibility","visible");p.setAttribute("fill-opacity",U);p.firstChild.nodeValue="[-]ALARMS="+la;a.registercontentsize(ha,fa)}function Ea(){var e=[],d,f=
[],J=[],n=[],l=[],l=[],c,b,g,x,D,P,O,G,R,T,y,E,X,aa;a.colword=a.colword.replace(/0x/gi,"#");a.headercolour=a.headercolour.replace(/0x/gi,"#");a.cellbackgroundcolour=a.cellbackgroundcolour.replace(/0x/gi,"#");a.fcolour=a.fcolour.replace(/0x/gi,"#");a.xarrowcolour=a.xarrowcolour.replace(/0x/gi,"#");a.bordercolour=a.bordercolour.replace(/0x/gi,"#");a.pluginbordercolour=a.pluginbordercolour.replace(/0x/gi,"#");a.pluginfillcolour=a.pluginfillcolour.replace(/0x/gi,"#");a.state0colour=a.state0colour.replace(/0x/gi,
"#");a.state1colour=a.state1colour.replace(/0x/gi,"#");a.state2colour=a.state2colour.replace(/0x/gi,"#");a.state3colour=a.state3colour.replace(/0x/gi,"#");a.state4colour=a.state4colour.replace(/0x/gi,"#");a.state5colour=a.state5colour.replace(/0x/gi,"#");a.state6colour=a.state6colour.replace(/0x/gi,"#");a.state7colour=a.state7colour.replace(/0x/gi,"#");a.state8colour=a.state8colour.replace(/0x/gi,"#");a.state9colour=a.state9colour.replace(/0x/gi,"#");L[0]=a.state0colour;L[1]=a.state1colour;L[2]=a.state2colour;
L[3]=a.state3colour;L[4]=a.state4colour;L[5]=a.state5colour;L[6]=a.state6colour;L[7]=a.state7colour;L[8]=a.state8colour;L[9]=a.state9colour;Q[0]=parseInt(a.state0blink);Q[1]=parseInt(a.state1blink);Q[2]=parseInt(a.state2blink);Q[3]=parseInt(a.state3blink);Q[4]=parseInt(a.state4blink);Q[5]=parseInt(a.state5blink);Q[6]=parseInt(a.state6blink);Q[7]=parseInt(a.state7blink);Q[8]=parseInt(a.state8blink);Q[9]=parseInt(a.state9blink);U=parseFloat(a.opacity);xa=.5*U;d=0;q=parseInt(a.rows);1>q&&(q=1);d=0;f=
a.colword.split(":");x=parseInt(a.xstart);D=parseInt(a.ystart);O=P=0;5>P&&(P=5);5>O&&(O=5);G=a.bordercolour;R=parseInt(a.borderthickness);1>R&&(R=1);5<R&&(R=5);g=a.headercolour;ma=a.cellbackgroundcolour;T=a.fcolour;y=parseInt(a.fnt);E=parseInt(a.fsiz);aa=a.pluginbordercolour;X=a.pluginfillcolour;ga=a.ttitle;c=k.length;z=Math.ceil(c/h/q);0==z&&(z=1);pa=z*q*h;for(b=0;b<c;b++)ba[b]="",qa[b]=!1,F[b]=0;for(b=0;b<c;b++)if(l=k[b].split(":"),1<l.length&&(ba[b]=l[1],ba[b]=ba[b].trim()),k[b]=l[0],0<k[b].length){for(w=
V[b]=0;w<k[b].length;w++)if(" "!=k[b].charAt(w)){V[b]=1;break}1==V[b]&&"@"==k[b].charAt(w)?(ra=V[b]=1,""==ba[b]&&(ba[b]=" "),l=k[b].split("|"),k[b]=l[0],S[b]=1,ca[b]=parseInt(ia[4]),1<l.length&&(ca[b]=parseInt(l[1]),0>ca[b]&&(ca[b]=-2)),2<l.length&&(S[b]=parseFloat(l[2]),0==S[b]&&(S[b]=1))):(V[b]=0,S[b]=1,ca[b]=0)}if(c<z*q*h)for(b=c;b<z*q*h;b++)k[b]=" ",ba[b]="",V[b]=0,S[b]=1,ca[b]=0,F[b]=0,qa[b]=!1;var w=[],l=[],sa=[],na=[],ta=[];for(b=0;b<h;b++)l[b]=0,sa[b]=0,na[b]=0,ta[b]=0;if(0<f.length)for(b=
0;b<f.length;b++)w=f[b].split(","),0<w.length&&(l[b]=parseInt(w[0]),1<w.length&&(sa[b]=parseInt(w[1])),2<w.length&&(na[b]=parseInt(w[2])),3<w.length&&(ta[b]=w[3]));c=q*h*z;f=1==y?"Times New Roman":2==y?"Arial":3==y?"Calibri":4==y?"Sans-Serif":5==y?"Verdana":6==y?"Century":"Arial";E=1==E?10:2==E?11:3==E?12:4==E?14:5==E?16:6==E?18:10;y="normal";M[0]=x;A[0]=D;for(c=D=0;c<h;c++){J[c]=ua[c].length;for(b=0;b<q*z;b++){y=k[b*h+c];for(w=0;w<y.length&&" "==y.charAt(w);w++);w<y.length&&y.charAt(w);y.length>
J[c]&&(J[c]=y.length+2)}e[c]=Math.round(J[c]*E*.65)+P;M[c+1]=M[c]+e[c]}0==d&&(d=1.2*E+O);oa=Math.round(a.name.length*E*.65);for(c=0;c<h;c++)H[c]=document.createElementNS("http://www.w3.org/2000/svg","rect"),H[c].setAttribute("x",M[c]),H[c].setAttribute("y",A[0]),H[c].setAttribute("width",e[c]),H[c].setAttribute("height",d),H[c].setAttribute("stroke-width",R),H[c].setAttribute("stroke",G),H[c].setAttribute("fill",g),H[c].setAttribute("stroke-opacity",U),H[c].setAttribute("fill-opacity",U),0==I?H[c].setAttribute("visibility",
"visible"):H[c].setAttribute("visibility","hidden"),v[c]=document.createElementNS("http://www.w3.org/2000/svg","text"),0==l[c]?(v[c].setAttribute("text-anchor","start"),v[c].setAttribute("x",M[c]+P),v[c].setAttribute("y",A[0]+d/2+O)):1==l[c]?(v[c].setAttribute("text-anchor","middle"),v[c].setAttribute("x",M[c]+e[c]/2),v[c].setAttribute("y",A[0]+d/2+O)):2==l[c]&&(v[c].setAttribute("text-anchor","end"),v[c].setAttribute("x",M[c]+e[c]-P),v[c].setAttribute("y",A[0]+d/2+O)),1==na[c]&&v[c].setAttribute("font-style",
"italic"),v[c].setAttribute("font-size",E),v[c].setAttribute("font-family",f),v[c].setAttribute("fill","0"),v[c].setAttribute("font-weight","bold"),v[c].setAttribute("width",e[c]),v[c].setAttribute("height",d),0==I?v[c].setAttribute("visibility","visible"):v[c].setAttribute("visibility","hidden"),b=document.createTextNode(ua[c]),v[c].appendChild(b),N.appendChild(H[c]),N.appendChild(v[c]);A[0]+=d;for(J=0;J<z;J++)for(b=0;b<q;b++)A[J*q+b+1]=A[b]+d;for(J=0;J<z;J++){var ya;ya=J*q*h;for(b=0;b<q;b++){var w;
w=b*h;for(c=0;c<h;c++)g=ya+w+c,y=1==sa[c]?"bold":"normal",t[g]=document.createElementNS("http://www.w3.org/2000/svg","rect"),t[g].setAttribute("x",M[c]),t[g].setAttribute("y",A[b]),t[g].setAttribute("width",e[c]),t[g].setAttribute("height",d),t[g].setAttribute("stroke-width",R),t[g].setAttribute("stroke",G),t[g].setAttribute("fill",ma),t[g].setAttribute("stroke-opacity",U),t[g].setAttribute("fill-opacity",U),t[g].setAttribute("visibility","visible"),m[g]=document.createElementNS("http://www.w3.org/2000/svg",
"text"),0==l[c]?(m[g].setAttribute("text-anchor","start"),m[g].setAttribute("x",M[c]+P),m[g].setAttribute("y",A[b]+d/2+O)):1==l[c]?(m[g].setAttribute("text-anchor","middle"),m[g].setAttribute("x",M[c]+e[c]/2),m[g].setAttribute("y",A[b]+d/2+O)):2==l[c]&&(m[g].setAttribute("text-anchor","end"),m[g].setAttribute("x",M[c]+e[c]-P),m[g].setAttribute("y",A[b]+d/2+O)),1==na[c]&&m[g].setAttribute("font-style","italic"),m[g].setAttribute("font-size",E),m[g].setAttribute("font-family",f),m[g].setAttribute("fill",
ta[c]),m[g].setAttribute("font-weight",y),0==I?m[g].setAttribute("visibility","visible"):m[g].setAttribute("visibility","hidden"),y=1==V[g]?document.createTextNode(" "):document.createTextNode(k[g]),0!=V[g]&&(k[g]=k[g].replace("@",""),k[g]=k[g].trim()),m[g].appendChild(y),0!=J||1==I?m[g].setAttribute("visibility","hidden"):m[g].setAttribute("visibility","visible"),0!=J||1==I?t[g].setAttribute("visibility","hidden"):t[g].setAttribute("visibility","visible")}}for(b=0;b<h;b++)D+=e[b];ha=D+x+x;fa=q*d+
A[0];if(0<ga.length||1<z)fa+=d;K=document.createElementNS("http://www.w3.org/2000/svg","rect");K.setAttribute("x",0);K.setAttribute("y",0);K.setAttribute("width",ha);K.setAttribute("height",fa);K.setAttribute("stroke",aa);K.setAttribute("fill",X);K.setAttribute("fill-opacity",.25);K.setAttribute("stroke-width",1);0==I?K.setAttribute("visibility","visible"):K.setAttribute("visibility","hidden");N.appendChild(K);for(b=0;b<z*q*h;b++)N.appendChild(t[b]),N.appendChild(m[b]);if(0<ga.length||1<z)0==ga.length&&
(ga=" "),n.length=0,n=ga.split(":"),O=P=x=0,1<n.length&&(2==n.length?x=parseInt(n[1]):3==n.length?(x=parseInt(n[1]),P=parseInt(n[2])):4==n.length&&(x=parseInt(n[1]),P=parseInt(n[2]),O=parseInt(n[3]))),y="normal",R="none",G="normal",0!=x&&(y="bold"),0!=P&&(R="underline"),0!=O&&(G="italic"),B=document.createElementNS("http://www.w3.org/2000/svg","text"),B.setAttribute("x",M[0]+D/2),B.setAttribute("y",A[q]+.7*d),B.setAttribute("font-size",E),B.setAttribute("font-family",f),B.setAttribute("text-decoration",
R),B.setAttribute("font-style",G),B.setAttribute("fill",T),B.setAttribute("font-weight",y),B.setAttribute("text-anchor","middle"),0==I?B.setAttribute("visibility","visible"):B.setAttribute("visibility","hidden"),n=document.createTextNode(n[0]),B.appendChild(n),N.appendChild(B),1<z&&(da="<0",u=document.createElementNS("http://www.w3.org/2000/svg","text"),u.setAttribute("x",M[0]+5),u.setAttribute("y",A[q]+.8*d),u.setAttribute("font-size",E),u.setAttribute("font-family",f),u.setAttribute("font-style",
"normal"),u.setAttribute("fill",T),u.setAttribute("text-anchor","left"),u.setAttribute("visibility","hidden"),u.addEventListener("click",va),u.addEventListener("mouseover",Y),u.addEventListener("mouseout",Z),n=document.createTextNode(da),u.appendChild(n),N.appendChild(u),ea="2>",r=document.createElementNS("http://www.w3.org/2000/svg","text"),r.setAttribute("x",M[h-1]+e[h-1]-5),r.setAttribute("y",A[q]+.8*d),r.setAttribute("font-size",E),r.setAttribute("font-family",f),r.setAttribute("font-style","normal"),
r.setAttribute("fill",T),r.setAttribute("text-anchor","end"),0==I?r.setAttribute("visibility","visible"):r.setAttribute("visibility","hidden"),r.addEventListener("click",wa),r.addEventListener("mouseover",Y),r.addEventListener("mouseout",Z),e=document.createTextNode(ea),r.appendChild(e),N.appendChild(r));za=0==I?"[-]ALARMS="+la:a.name;p=document.createElementNS("http://www.w3.org/2000/svg","text");p.setAttribute("x",0);p.setAttribute("y",12);p.setAttribute("font-size",14);p.setAttribute("font-family",
"Arial");p.setAttribute("font-style","normal");p.setAttribute("fill",a.xarrowcolour);p.setAttribute("font-weight","bold");p.setAttribute("text-anchor","left");p.setAttribute("visibility","visible");p.setAttribute("fill-opacity","opacity");e=document.createTextNode(za);p.appendChild(e);p.addEventListener("click",ka);p.addEventListener("mouseover",Y);p.addEventListener("mouseout",Z);C=document.createElementNS("http://www.w3.org/2000/svg","rect");C.setAttribute("x",0);C.setAttribute("y",0);C.setAttribute("width",
ha);C.setAttribute("height",fa-d-10);C.setAttribute("stroke",aa);C.setAttribute("fill",X);C.setAttribute("fill-opacity",0);C.setAttribute("stroke-opacity",0);C.setAttribute("stroke-width",1);N.appendChild(C);N.appendChild(p);C.addEventListener("click",Da);C.addEventListener("mouseover",Y);C.addEventListener("mouseout",Z);0==I?a.registercontentsize(ha,fa):a.registercontentsize(oa,20);1==ra&&(d=getcycletime(),d=d.trim(),d=parseInt(d),isNaN(d)?d=5:0>=d&&(d=5),setTimeout(Aa,1E3),Ba=setInterval(function(){Aa()},
1E3*d),Ca=setInterval(function(){var a,b;1==I&&0<ja&&(0<ja&&(0==W||2==W)?p.setAttribute("fill-opacity",xa):p.setAttribute("fill-opacity",U));b=mack_status();for(a=0;a<pa;a++)qa[a]||b?t[a].setAttribute("fill",L[F[a]]):1==Q[F[a]]?2==W||3==W?t[a].setAttribute("fill",ma):t[a].setAttribute("fill",L[F[a]]):2==Q[F[a]]?1==W||3==W?t[a].setAttribute("fill",ma):t[a].setAttribute("fill",L[F[a]]):t[a].setAttribute("fill",L[F[a]]);W++;3<W&&(W=0)},500))}function Aa(){var a,d,f;for(d=ja=0;d<pa;d++)1==V[d]?(a=somefunction(k[d]),
f=a.split(","),T="",a=f[0],F[d]=1<f.length?parseInt(f[1]):0,0<F[d]&&(ja=1),9<F[d]&&(G.trace(1,"state > 9:"+F[d]),F[d]=9),0>F[d]&&(G.trace(1,"state < 0:"+F[d]),F[d]=0),2<f.length&&(T=f[2]),j=Math.floor(d/h),"i"==X[j]||"I"==X[j]?(a=parseInt(a),isNaN(a)&&(a=0),1!=S[d]&&(a*=S[d]),m[d].firstChild.nodeValue=a+T):"f"==X[j]||"F"==X[j]?(a=parseFloat(a),isNaN(a)&&(a=0),1!=S[d]&&(a*=S[d]),m[d].firstChild.nodeValue=a.toFixed(ca[d])+T):m[d].firstChild.nodeValue=a+" "+T):m[d].firstChild.nodeValue=k[d]}var G=null,
a=null,N=null,ha,fa,q,la,h,I=1,x=0,z=1,u,r,p,za,oa,da,ea,K,C,ga,B,ma,D=[],k=[],m=[],t=[],ua=[],v=[],H=[],M=[],A=[],ba=[],Ba,Ca,ra,V=[],S=[],ca=[],X=[],pa,L=[],Q=[],F=[],W=0,ja=0,qa=[],ia=[],T,ja=0,U,xa;this.registerplugin=function(e,d,f){G=e;a=f;a.registerattribute("ver","0");a.registerattribute("tabletags","");a.registerattribute("rows","4");a.registerattribute("columns","5");a.registerattribute("colword","1,1,0,0:0:1,1,1,0:0:0");a.registerattribute("xstart","10");a.registerattribute("ystart","10");
a.registerattribute("bordercolour","0x000000");a.registerattribute("borderthickness","2");a.registerattribute("headercolour","0x0000FF");a.registerattribute("cellbackgroundcolour","0xFFFF00");a.registerattribute("fcolour","0xFFFF00");a.registerattribute("xarrowcolour","0xFFFF00");a.registerattribute("fnt","5");a.registerattribute("fsiz","2");a.registerattribute("opacity","1.0");a.registerattribute("ttitle","SUMMARY OF ALARMS");a.registerattribute("pluginbordercolour","0x000000");a.registerattribute("pluginfillcolour",
"0x0000FF");a.registerattribute("state0colour","0xFFFF00");a.registerattribute("state1colour","0xFFA500");a.registerattribute("state2colour","0xFF0000");a.registerattribute("state3colour","0x8A2BE2");a.registerattribute("state4colour","0x0000FF");a.registerattribute("state5colour","0xFFFF00");a.registerattribute("state6colour","0xFFA500");a.registerattribute("state7colour","0xFF0000");a.registerattribute("state8colour","0x8A2BE2");a.registerattribute("state9colour","0x0000FF");a.registerattribute("state0blink",
"0");a.registerattribute("state1blink","1");a.registerattribute("state2blink","2");a.registerattribute("state3blink","1");a.registerattribute("state4blink","2");a.registerattribute("state5blink","0");a.registerattribute("state6blink","1");a.registerattribute("state7blink","2");a.registerattribute("state8blink","1");a.registerattribute("state9blink","2");a.registerattribute("state0","state0");a.registerattribute("state1","state1");a.registerattribute("state2","state2");a.registerattribute("state3",
"state3");a.registerattribute("state4","state4");a.registerattribute("state5","state5");a.registerattribute("state6","state6");a.registerattribute("state7","state7");a.registerattribute("state8","state8");a.registerattribute("state9","state9");a.handcursor=!1;a.registercontentsize(512,512);N=document.createElementNS("http://www.w3.org/2000/svg","svg");N.style.width="100%";N.style.height="100%";a.sprite.appendChild(N);1==Number(a.ver)&&G.trace(1,"hello from plugin["+a.name+"] version = 1.0");k.length=
0;h=5;1>h&&(h=1);D=getAlarms().split(";");0<D.length&&D.length--;d="SrNo;Tag;Drscription;Units;Status";la=f=D.length;100<f&&(f=100);for(e=0;e<f;e++)ia=getattr(D[e]).split(","),d+=";"+(e+1)+";"+D[e]+";"+ia[1]+";"+ia[2]+";@"+D[e],X[e]=ia[0];k=d.split(";");e=k.length;""==k[e-1]&&(k.length=e-1);d=[];for(e=0;e<h;e++)d=k[e].split(":"),ua[e]=d[0];for(e=0;e<h;e++)k.shift();d.length=0;Ea()};this.unloadplugin=function(){C.removeEventListener("click",ka);C.removeEventListener("mouseover",Y);C.removeEventListener("mouseout",
Z);p.removeEventListener("click",ka);p.removeEventListener("mouseover",Y);p.removeEventListener("mouseout",Z);1<z&&(u.removeEventListener("click",va),u.removeEventListener("mouseover",Y),u.removeEventListener("mouseout",Z),r.removeEventListener("click",wa),r.removeEventListener("mouseover",Y),r.removeEventListener("mouseout",Z));1==ra&&(clearInterval(Ba),clearInterval(Ca));G=a=null};this.onresize=function(a,d){return!1}};
