var krpanoplugin=function(){function V(b){a.handcursor=!0}function W(b){a.handcursor=!1}function X(){var b;if(0==A){A=1;for(b=0;2>b;b++)c[b].setAttribute("visibility","hidden");k.setAttribute("visibility","hidden");e.setAttribute("visibility","hidden");f.firstChild.nodeValue=a.name;a.registercontentsize(P,15)}else{for(b=A=0;2>b;b++)c[b].setAttribute("visibility","visible");k.setAttribute("visibility","visible");e.setAttribute("visibility","visible");f.setAttribute("fill-opacity",q);f.firstChild.nodeValue=
"";a.registercontentsize(H,L)}}function fa(){var b,I,t,m,x,M,F,d;a.bordercolour=a.bordercolour.replace(/0x/gi,"#");a.fillcolour=a.fillcolour.replace(/0x/gi,"#");a.emptycolour=a.emptycolour.replace(/0x/gi,"#");a.fcolour=a.fcolour.replace(/0x/gi,"#");a.xarrowcolour=a.xarrowcolour.replace(/0x/gi,"#");a.state0colour=a.state0colour.replace(/0x/gi,"#");a.state1colour=a.state1colour.replace(/0x/gi,"#");a.state2colour=a.state2colour.replace(/0x/gi,"#");a.state3colour=a.state3colour.replace(/0x/gi,"#");a.state4colour=
a.state4colour.replace(/0x/gi,"#");a.state5colour=a.state5colour.replace(/0x/gi,"#");a.state6colour=a.state6colour.replace(/0x/gi,"#");a.state7colour=a.state7colour.replace(/0x/gi,"#");a.state8colour=a.state8colour.replace(/0x/gi,"#");a.state9colour=a.state9colour.replace(/0x/gi,"#");n[0]=a.state0colour;n[1]=a.state1colour;n[2]=a.state2colour;n[3]=a.state3colour;n[4]=a.state4colour;n[5]=a.state5colour;n[6]=a.state6colour;n[7]=a.state7colour;n[8]=a.state8colour;n[9]=a.state9colour;p[0]=parseInt(a.state0blink);
p[1]=parseInt(a.state1blink);p[2]=parseInt(a.state2blink);p[3]=parseInt(a.state3blink);p[4]=parseInt(a.state4blink);p[5]=parseInt(a.state5blink);p[6]=parseInt(a.state6blink);p[7]=parseInt(a.state7blink);p[8]=parseInt(a.state8blink);p[9]=parseInt(a.state9blink);q=parseFloat(a.opacity);N=.5*q;b=a.bordercolour;r=parseInt(a.borderwidth);Y=a.fillcolour;Z=a.emptycolour;I=a.fcolour;t=parseInt(a.fnt);m=parseInt(a.fsiz);x=parseInt(a.just);M=parseInt(a.bold);F=parseInt(a.italic);y=parseInt(a.barwidth);z=parseInt(a.barheight);
g=100;Q=a.bartag.replace("@"," ").trim();u=getattr(Q).split(",");v=parseFloat(a.minvalue);B=parseFloat(a.maxvalue);D=a.description;0==D.length&&(D=u[1]);E=a.units;0==E.length&&(E=u[2]);R=0==a.decimals.length?parseInt(u[4]):parseInt(a.decimals);S=parseFloat(a.mult);t=1==t?"Times New Roman":2==t?"Arial":3==t?"Calibri":4==t?"Sans-Serif":5==t?"Verdana":6==t?"Century":"Arial";m=1==m?10:2==m?11:3==m?12:4==m?14:5==m?16:6==m?18:10;M=1==M?"bold":"normal";J=g.toFixed(R);T=z;var h;h=parseInt(u[3]);0>=h&&(h=
J.length);h=h+E.length+15;h<D.length&&(h=D.length);var O;h=Math.round(h*m*.65);P=Math.round(a.name.length*m*.65);O=1.1*m;h<y+2*r&&(h=y+2*r);for(d=0;2>d;d++){c[d]=document.createElementNS("http://www.w3.org/2000/svg","text");0==d?c[d].setAttribute("y",T+O+3):c[d].setAttribute("y",T+2*O+3);0==x?(c[d].setAttribute("text-anchor","start"),c[d].setAttribute("x",0)):1==x?(c[d].setAttribute("text-anchor","middle"),c[d].setAttribute("x",h/2)):2==x&&(c[d].setAttribute("text-anchor","end"),c[d].setAttribute("x",
h));1==F&&c[d].setAttribute("font-style","italic");c[d].setAttribute("font-size",m);c[d].setAttribute("font-family",t);c[d].setAttribute("fill",I);c[d].setAttribute("font-weight",M);c[d].setAttribute("visibility","visible");var G;G=0==d?document.createTextNode(J+" "+E):document.createTextNode(D);c[d].appendChild(G);w.appendChild(c[d])}U=r+(h-y)/2;aa=r;k=document.createElementNS("http://www.w3.org/2000/svg","rect");k.setAttribute("x",U);k.setAttribute("y",aa);k.setAttribute("width",y);k.setAttribute("height",
z);k.setAttribute("stroke-width",r);k.setAttribute("stroke",b);k.setAttribute("fill",Z);k.setAttribute("stroke-opacity",q);k.setAttribute("fill-opacity",q);k.setAttribute("visibility","visible");w.appendChild(k);g<v&&(g=v);g>B&&(g=B);x=r;I=(z-2*x)*(g-v)/(B-v);e=document.createElementNS("http://www.w3.org/2000/svg","rect");e.setAttribute("x",U+x);e.setAttribute("y",z-I);e.setAttribute("width",y-2*x);e.setAttribute("height",I);e.setAttribute("stroke-width",0);e.setAttribute("stroke",b);e.setAttribute("fill",
Y);e.setAttribute("stroke-opacity",q);e.setAttribute("fill-opacity",q);e.setAttribute("visibility","visible");w.appendChild(e);H=y;h>y&&(H=h);L=z+2*O+5;ba=1==A?a.name:"";f=document.createElementNS("http://www.w3.org/2000/svg","text");f.setAttribute("x",r);f.setAttribute("y",8+r);f.setAttribute("font-size",12);f.setAttribute("font-family","Arial");f.setAttribute("font-style","normal");f.setAttribute("fill",a.xarrowcolour);f.setAttribute("font-weight","bold");f.setAttribute("text-anchor","left");f.setAttribute("visibility",
"visible");b=document.createTextNode(ba);f.appendChild(b);w.appendChild(f);targetcell=document.createElementNS("http://www.w3.org/2000/svg","rect");targetcell.setAttribute("x",0);targetcell.setAttribute("y",0);targetcell.setAttribute("width",H);targetcell.setAttribute("height",L);targetcell.setAttribute("fill-opacity",0);targetcell.setAttribute("fill",0);w.appendChild(targetcell);targetcell.addEventListener("click",X);targetcell.addEventListener("mouseover",V);targetcell.addEventListener("mouseout",
W);1==A?a.registercontentsize(P,15):a.registercontentsize(H,L);b=getcycletime();b=b.trim();b=parseInt(b);isNaN(b)?b=5:0>=b&&(b=5);setTimeout(ca,1E3);da=setInterval(function(){ca()},1E3*b);ea=setInterval(function(){ga||mack_status()?K(1):(1==p[l]?2==C||3==C?K(0):K(1):2==p[l]&&(1==C||3==C?K(0):K(1)),C++,3<C&&(C=0))},500)}function ca(a){a=somefunction(Q).split(",");F="";g="f"==u[0]||"F"==u[0]?parseFloat(a[0]):"i"==u[0]||"I"==u[0]?parseInt(a[0]):0;isNaN(g)&&(g=0);1<a.length?(l=parseInt(a[1]),9<l&&(console.log("?level bar, state>9: "+
l),l=9),0>l&&(console.log("?level bar, state<0: "+l),l=0),2<a.length&&(F=a[2])):l=0;1!=S&&(g*=S);g<v&&(g=v);g>B&&(g=B);a=(z-2*r)*(g-v)/(B-v);e.setAttribute("y",z-a);e.setAttribute("height",a);e.setAttribute("fill",n[l]);J=g.toFixed(R)+" "+E+F;c[0].setAttribute("fill",n[l]);c[0].firstChild.nodeValue=J}function K(a){1==a?(0<l&&1==A&&f.setAttribute("fill-opacity",q),e.setAttribute("fill-opacity",q),c[0].setAttribute("fill-opacity",q)):(0<l&&1==A&&f.setAttribute("fill-opacity",N),e.setAttribute("fill-opacity",
N),c[0].setAttribute("fill-opacity",N))}var G=null,a=null,w=null,J,c=[],k,e,U,aa,T,Q,g,v,B,da,ea,E,D,R,S,y,z,r,Y,Z,n=[],p=[],l,C=0,ga,q,N,f,ba,P,A=1,u=[],F,H,L;this.registerplugin=function(b,c,e){G=b;a=e;a.registerattribute("ver","0");a.registerattribute("fillcolour","0x0000FF");a.registerattribute("emptycolour","0xFFFFFF");a.registerattribute("barwidth","20");a.registerattribute("barheight","100");a.registerattribute("bordercolour","0x000000");a.registerattribute("borderwidth","1");a.registerattribute("fcolour",
"0xFF0000");a.registerattribute("xarrowcolour","0xFFFF00");a.registerattribute("fnt","5");a.registerattribute("fsiz","4");a.registerattribute("just","0");a.registerattribute("italic","0");a.registerattribute("bold","0");a.registerattribute("bartag","@[default]Tag 0");a.registerattribute("maxvalue","100");a.registerattribute("minvalue","0");a.registerattribute("units","");a.registerattribute("description","");a.registerattribute("decimals","");a.registerattribute("mult","1.0");a.registerattribute("opacity",
"1.0");a.registerattribute("state0colour","0xFFFF00");a.registerattribute("state1colour","0xFFA500");a.registerattribute("state2colour","0xFF0000");a.registerattribute("state3colour","0x8A2BE2");a.registerattribute("state4colour","0x0000FF");a.registerattribute("state5colour","0xFFFF00");a.registerattribute("state6colour","0xFFA500");a.registerattribute("state7colour","0xFF0000");a.registerattribute("state8colour","0x8A2BE2");a.registerattribute("state9colour","0x0000FF");a.registerattribute("state0blink",
"0");a.registerattribute("state1blink","1");a.registerattribute("state2blink","2");a.registerattribute("state3blink","1");a.registerattribute("state4blink","2");a.registerattribute("state5blink","0");a.registerattribute("state6blink","1");a.registerattribute("state7blink","2");a.registerattribute("state8blink","1");a.registerattribute("state9blink","2");a.handcursor=!1;a.registercontentsize(100,100);w=document.createElementNS("http://www.w3.org/2000/svg","svg");w.style.width="100%";w.style.height=
"100%";a.sprite.appendChild(w);1==Number(a.ver)&&G.trace(1,"hello from plugin["+a.name+"] version = 1.0");fa()};this.unloadplugin=function(){targetcell.removeEventListener("click",X);targetcell.removeEventListener("mouseover",V);targetcell.removeEventListener("mouseout",W);clearInterval(da);clearInterval(ea);G=a=null}};
