var krpanoplugin=function(){function K(b){1==m&&(a.handcursor=!0)}function L(b){1==m&&(a.handcursor=!1)}function M(a){0!=m&&"RW"==F&&(n.setAttribute("fill",d[0]),1!=buffer2_not_recd&&""!=w&&putval1(w))}function N(a){0!=m&&"RW"==(F=getaccess())&&(n.setAttribute("fill","#000000"),1!=buffer1_not_recd&&""!=w&&(putval(w),f.firstChild.nodeValue="Down"))}function U(){var b,c,x,e,G,y,H,t,I,E,F,z;a.bordercolour=a.bordercolour.replace(/0x/gi,"#");a.state0colour=a.state0colour.replace(/0x/gi,"#");a.state1colour=
a.state1colour.replace(/0x/gi,"#");a.state2colour=a.state2colour.replace(/0x/gi,"#");a.state3colour=a.state3colour.replace(/0x/gi,"#");a.state4colour=a.state4colour.replace(/0x/gi,"#");a.state5colour=a.state5colour.replace(/0x/gi,"#");a.state6colour=a.state6colour.replace(/0x/gi,"#");a.state7colour=a.state7colour.replace(/0x/gi,"#");a.state8colour=a.state8colour.replace(/0x/gi,"#");a.state9colour=a.state9colour.replace(/0x/gi,"#");d[0]=a.state0colour;d[1]=a.state1colour;d[2]=a.state2colour;d[3]=a.state3colour;
d[4]=a.state4colour;d[5]=a.state5colour;d[6]=a.state6colour;d[7]=a.state7colour;d[8]=a.state8colour;d[9]=a.state9colour;p[0]=parseInt(a.state0blink);p[1]=parseInt(a.state1blink);p[2]=parseInt(a.state2blink);p[3]=parseInt(a.state3blink);p[4]=parseInt(a.state4blink);p[5]=parseInt(a.state5blink);p[6]=parseInt(a.state6blink);p[7]=parseInt(a.state7blink);p[8]=parseInt(a.state8blink);p[9]=parseInt(a.state9blink);u[0]=a.state0label;u[1]=a.state1label;u[2]=a.state2label;u[3]=a.state3label;u[4]=a.state4label;
u[5]=a.state5label;u[6]=a.state6label;u[7]=a.state7label;u[8]=a.state8label;u[9]=a.state9label;z=parseFloat(a.opacity);c=0;x=a.bordercolour;e=parseInt(a.borderthickness);1>e&&(e=1);5<e&&(e=5);G=a.fcolour;y=parseInt(a.fnt);b=parseInt(a.fsiz);H=parseInt(a.fjust);t=parseInt(a.fbold);F=parseInt(a.fitalic);w=a.buttoncommand;w=w.replace("@","");w=w.trim();k=0;O=!1;m=0;v=a.buttonvar.trim();var J=" ";0<v.length&&("@"==v.charAt(0)&&(m=1),1==m?(c=v.lastIndexOf("/"),0<c?J=v.substring(c+1)+"    ":(c=v.lastIndexOf("]"),
0<c?J=v.substring(c+1)+"    ":word1=v)):m=0);y=1==y?"Times New Roman":2==y?"Arial":3==y?"Calibri":4==y?"Sans-Serif":5==y?"Verdana":6==y?"Century":"Arial";I=1==b?10:2==b?11:3==b?12:4==b?14:5==b?16:6==b?18:10;E="normal";q=l=e;b=J.length+1;1>b&&(b=1);b=Math.round(b*I*.65);c=1.25*I;E=1==t?"bold":"normal";n=document.createElementNS("http://www.w3.org/2000/svg","rect");n.setAttribute("x",l);n.setAttribute("y",q);n.setAttribute("width",b+10);n.setAttribute("height",c+10);n.setAttribute("stroke-width",e);
n.setAttribute("stroke",x);n.setAttribute("fill",d[0]);n.setAttribute("stroke-opacity",z);n.setAttribute("fill-opacity",z);g=document.createElementNS("http://www.w3.org/2000/svg","rect");g.setAttribute("x",l+5);g.setAttribute("y",q+5);g.setAttribute("width",b);g.setAttribute("height",c);g.setAttribute("stroke-width",1);g.setAttribute("stroke",x);g.setAttribute("fill",d[0]);g.setAttribute("stroke-opacity",z);g.setAttribute("fill-opacity",z);t=document.createElementNS("http://www.w3.org/2000/svg","line");
t.setAttribute("x1",l);t.setAttribute("y1",q);t.setAttribute("x2",l+5);t.setAttribute("y2",q+5);t.setAttribute("stroke",x);t.setAttribute("stroke-width",1);t.setAttribute("stroke-opacity",z);var A=document.createElementNS("http://www.w3.org/2000/svg","line");A.setAttribute("x1",l);A.setAttribute("y1",q+c+10);A.setAttribute("x2",l+5);A.setAttribute("y2",q+c+5);A.setAttribute("stroke",x);A.setAttribute("stroke-width",1);A.setAttribute("stroke-opacity",z);var B=document.createElementNS("http://www.w3.org/2000/svg",
"line");B.setAttribute("x1",l+b+10);B.setAttribute("y1",q);B.setAttribute("x2",l+b+5);B.setAttribute("y2",q+5);B.setAttribute("stroke",x);B.setAttribute("stroke-width",1);B.setAttribute("stroke-opacity",z);var C=document.createElementNS("http://www.w3.org/2000/svg","line");C.setAttribute("x1",l+b+10);C.setAttribute("y1",q+c+10);C.setAttribute("x2",l+b+5);C.setAttribute("y2",q+c+5);C.setAttribute("stroke",x);C.setAttribute("stroke-width",1);C.setAttribute("stroke-opacity",z);f=document.createElementNS("http://www.w3.org/2000/svg",
"text");x=q+5+.8*c;0==H?(f.setAttribute("text-anchor","start"),f.setAttribute("x",l+5)):1==H?(f.setAttribute("text-anchor","middle"),f.setAttribute("x",l+5+b/2)):2==H&&(f.setAttribute("text-anchor","end"),f.setAttribute("x",l+b+5));1==F&&f.setAttribute("font-style","italic");f.setAttribute("font-size",I);f.setAttribute("font-family",y);f.setAttribute("fill",G);f.setAttribute("font-weight",E);f.setAttribute("y",x);G=document.createTextNode(J);0!=m&&(v=v.replace("@","").trim());f.appendChild(G);h=document.createElementNS("http://www.w3.org/2000/svg",
"rect");h.setAttribute("x",l);h.setAttribute("y",q);h.setAttribute("width",b+10);h.setAttribute("height",c+15);h.setAttribute("fill-opacity",0);h.setAttribute("fill",0);f.setAttribute("visibility","visible");g.setAttribute("visibility","visible");h.setAttribute("visibility","visible");P=b+2*e+10;Q=c+2*e+10;a.registercontentsize(P,Q);r.appendChild(n);r.appendChild(g);r.appendChild(t);r.appendChild(A);r.appendChild(B);r.appendChild(C);r.appendChild(f);r.appendChild(h);h.addEventListener("mouseup",M);
h.addEventListener("mousedown",N);h.addEventListener("mouseover",K);h.addEventListener("mouseout",L);1==m&&(e=getcycletime(),e=e.trim(),e=parseInt(e),isNaN(e)?e=1:0>=e&&(e=1),setTimeout(R,1E3),S=setInterval(function(){R()},1E3*e),T=setInterval(function(){0!=m&&(O||mack_status()?(g.setAttribute("fill",d[k]),D=0):(0==p[k]?g.setAttribute("fill",d[k]):1==p[k]?2==D||3==D?g.setAttribute("fill",d[0]):g.setAttribute("fill",d[k]):2==p[k]&&(1==D||3==D?g.setAttribute("fill",d[0]):g.setAttribute("fill",d[k])),
D++,3<D&&(D=0)))},500))}function R(){var a=[],c;1!=buffer1_not_recd&&1!=buffer2_not_recd&&1==m&&(c=somefunction(v),a.length=0,a=c.split(","),k=1<a.length?parseInt(a[1]):0,9<k&&(console.log("state out of range="+k),k=9),0>k&&(console.log("state out of range="+k),k=0),f.firstChild.nodeValue=u[k])}var E=null,a=null,r=null,P,Q,v,f,g,n,h,l,q,w,S,T,m,F="",p=[],d=[],u=[],k,D=0,O;this.registerplugin=function(b,c,d){E=b;a=d;a.registerattribute("ver","0");a.registerattribute("buttonvar","@Tag 1");a.registerattribute("bordercolour",
"0x000000");a.registerattribute("borderthickness","2");a.registerattribute("fcolour","0xFF0000");a.registerattribute("fnt","5");a.registerattribute("fsiz","4");a.registerattribute("fbold","0");a.registerattribute("fitalic","0");a.registerattribute("fjust","1");a.registerattribute("buttoncommand","");a.registerattribute("opacity","0.5");a.registerattribute("state0colour","0xFFFF00");a.registerattribute("state1colour","0xFFA500");a.registerattribute("state2colour","0xFF0000");a.registerattribute("state3colour",
"0x8A2BE2");a.registerattribute("state4colour","0x0000FF");a.registerattribute("state5colour","0xFFFF00");a.registerattribute("state6colour","0xFFA500");a.registerattribute("state7colour","0xFF0000");a.registerattribute("state8colour","0x8A2BE2");a.registerattribute("state9colour","0x0000FF");a.registerattribute("state0blink","0");a.registerattribute("state1blink","1");a.registerattribute("state2blink","2");a.registerattribute("state3blink","1");a.registerattribute("state4blink","2");a.registerattribute("state5blink",
"0");a.registerattribute("state6blink","1");a.registerattribute("state7blink","2");a.registerattribute("state8blink","1");a.registerattribute("state9blink","2");a.registerattribute("state0label","state0");a.registerattribute("state1label","state1");a.registerattribute("state2label","state2");a.registerattribute("state3label","state3");a.registerattribute("state4label","state4");a.registerattribute("state5label","state5");a.registerattribute("state6label","state6");a.registerattribute("state7label",
"state7");a.registerattribute("state8label","state8");a.registerattribute("state9label","state9");a.handcursor=!1;a.registercontentsize(100,100);r=document.createElementNS("http://www.w3.org/2000/svg","svg");r.style.width="100%";r.style.height="100%";a.sprite.appendChild(r);1==Number(a.ver)&&E.trace(1,"hello from plugin["+a.name+"] version = 1.0");a.buttonvar=a.buttonvar.replace("\n","");a.buttonvar=a.buttonvar.replace("\r","");a.buttonvar=a.buttonvar.replace("\t","");U()};this.unloadplugin=function(){h.removeEventListener("mouseup",
M);h.removeEventListener("mousedown",N);h.removeEventListener("mouseover",K);h.removeEventListener("mouseout",L);1==m&&(clearInterval(S),clearInterval(T));E=a=null};this.onresize=function(a,c){return!1}};
