var krpanoplugin=function(){function K(){0==v?(v=1,e.setAttribute("visibility","hidden"),d.setAttribute("visibility","hidden"),b.firstChild.nodeValue=a.name,a.registercontentsize(L,15)):(v=0,e.setAttribute("visibility","visible"),d.setAttribute("visibility","visible"),b.firstChild.nodeValue="",b.setAttribute("fill-opacity",C),a.registercontentsize(M,N))}function O(g){a.handcursor=!0}function P(g){a.handcursor=!1}function ca(){var g,w,A,c,B,q,l,G,S,Q,T;a.bordercolour=a.bordercolour.replace(/0x/gi,
"#");a.cellbackgroundcolour=a.cellbackgroundcolour.replace(/0x/gi,"#");a.fcolour=a.fcolour.replace(/0x/gi,"#");a.xarrowcolour=a.xarrowcolour.replace(/0x/gi,"#");a.state0colour=a.state0colour.replace(/0x/gi,"#");a.state1colour=a.state1colour.replace(/0x/gi,"#");a.state2colour=a.state2colour.replace(/0x/gi,"#");a.state3colour=a.state3colour.replace(/0x/gi,"#");a.state4colour=a.state4colour.replace(/0x/gi,"#");a.state5colour=a.state5colour.replace(/0x/gi,"#");a.state6colour=a.state6colour.replace(/0x/gi,
"#");a.state7colour=a.state7colour.replace(/0x/gi,"#");a.state8colour=a.state8colour.replace(/0x/gi,"#");a.state9colour=a.state9colour.replace(/0x/gi,"#");h[0]=a.state0colour;h[1]=a.state1colour;h[2]=a.state2colour;h[3]=a.state3colour;h[4]=a.state4colour;h[5]=a.state5colour;h[6]=a.state6colour;h[7]=a.state7colour;h[8]=a.state8colour;h[9]=a.state9colour;m[0]=parseInt(a.state0blink);m[1]=parseInt(a.state1blink);m[2]=parseInt(a.state2blink);m[3]=parseInt(a.state3blink);m[4]=parseInt(a.state4blink);m[5]=
parseInt(a.state5blink);m[6]=parseInt(a.state6blink);m[7]=parseInt(a.state7blink);m[8]=parseInt(a.state8blink);m[9]=parseInt(a.state9blink);C=parseFloat(a.opacity);U=.5*C;n[0]=a.state0;n[1]=a.state1;n[2]=a.state2;n[3]=a.state3;n[4]=a.state4;n[5]=a.state5;n[6]=a.state6;n[7]=a.state7;n[8]=a.state8;n[9]=a.state9;w=0;x=a.celltag.replace("@","").trim();H=V=1;var y=x;c=y.lastIndexOf("/");0<c?y=x.substring(c+1):(c=y.lastIndexOf("]"),0<c&&(y=x.substring(c+1)));r=getattr(x).split(",");t=a.description;0==t.length&&
(t=r[1]);u=a.units;0==u.length&&(u=r[2]);F=parseFloat(a.mult);I=parseInt(a.decimals);0==I.length&&(I=r[4]);W=parseInt(a.stateind);A=a.bordercolour;c=parseInt(a.borderthickness);R=1;0>=c&&(R=0);1>c&&(c=1);5<c&&(c=5);J=a.cellbackgroundcolour;B=a.fcolour;q=parseInt(a.fnt);l=parseInt(a.fsiz);G=parseInt(a.fjust);S=parseInt(a.fbold);T=parseInt(a.fitalic);f=0;X=!1;q=1==q?"Times New Roman":2==q?"Arial":3==q?"Calibri":4==q?"Sans-Serif":5==q?"Verdana":6==q?"Century":"Arial";l=1==l?10:2==l?11:3==l?12:4==l?14:
5==l?16:6==l?18:10;Q="normal";D=E=c;g=parseInt(r[3]);0>=g&&(g=y.length);g=t.length+g+u.length+12;1>g&&(g=1);g=Math.round(g*l*.6)+5;w=1.1*l+5;L=Math.round(a.name.length*l*.65);Q=1==S?"bold":"normal";e=document.createElementNS("http://www.w3.org/2000/svg","rect");e.setAttribute("x",E);e.setAttribute("y",D);e.setAttribute("width",g);e.setAttribute("height",w);e.setAttribute("stroke-width",c);e.setAttribute("stroke",A);e.setAttribute("fill",J);e.setAttribute("fill-opacity",C);e.setAttribute("stroke-opacity",
C);1==v?e.setAttribute("visibility","hidden"):e.setAttribute("visibility","visible");k=document.createElementNS("http://www.w3.org/2000/svg","rect");k.setAttribute("x",E);k.setAttribute("y",D);k.setAttribute("width",g);k.setAttribute("height",w);k.setAttribute("fill-opacity",0);k.setAttribute("fill",0);d=document.createElementNS("http://www.w3.org/2000/svg","text");0==G?(d.setAttribute("text-anchor","start"),d.setAttribute("x",E+5),d.setAttribute("y",D+w/2+5)):1==G?(d.setAttribute("text-anchor","middle"),
d.setAttribute("x",E+g/2),d.setAttribute("y",D+w/2+5)):2==G&&(d.setAttribute("text-anchor","end"),d.setAttribute("x",E+g-5),d.setAttribute("y",D+w/2+5));1==T&&d.setAttribute("font-style","italic");d.setAttribute("font-size",l);d.setAttribute("font-family",q);d.setAttribute("fill",B);d.setAttribute("font-weight",Q);y=document.createTextNode(t+" "+y+" "+u);0!=V&&(x=x.replace("@","").trim());d.appendChild(y);0==v?d.setAttribute("visibility","visible"):d.setAttribute("visibility","hidden");0>=R&&e.setAttribute("visibility",
"hidden");M=g+2*c;N=w+2*c;1==v?a.registercontentsize(L,15):a.registercontentsize(M,N);z.appendChild(e);z.appendChild(d);k.addEventListener("click",K);k.addEventListener("mouseover",O);k.addEventListener("mouseout",P);Y=0==v?"":a.name;b=document.createElementNS("http://www.w3.org/2000/svg","text");b.setAttribute("x",c);b.setAttribute("y",8+c);b.setAttribute("font-size",12);b.setAttribute("font-family","Arial");b.setAttribute("font-style","normal");b.setAttribute("fill",a.xarrowcolour);b.setAttribute("font-weight",
"bold");b.setAttribute("text-anchor","left");b.setAttribute("visibility","visible");c=document.createTextNode(Y);b.appendChild(c);z.appendChild(b);z.appendChild(k);1==H&&(c=getcycletime(),c=c.trim(),c=parseInt(c),isNaN(c)?c=5:0>=c&&(c=5),setTimeout(Z,1E3),aa=setInterval(function(){Z()},1E3*c),ba=setInterval(function(){1==v&&(0<f&&(0==p||2==p)?b.setAttribute("fill-opacity",U):b.setAttribute("fill-opacity",C));X||mack_status()?(e.setAttribute("fill",h[f]),p=0):(1==m[f]?2==p||3==p?e.setAttribute("fill",
J):e.setAttribute("fill",h[f]):2==m[f]?1==p||3==p?e.setAttribute("fill",J):e.setAttribute("fill",h[f]):e.setAttribute("fill",h[f]),p++,3<p&&(p=0))},500))}function Z(){var a,b;1==H?(a=somefunction(x),b=a.split(","),f=0,a=b[0],1<b.length&&(f=parseInt(b[1])),A="",2<b.length&&(A=b[2]),e.setAttribute("fill",h[f]),0>f&&(B.trace(1,"invalid state="+f),f=0),9<f&&(B.trace(1,"invalid state="+f),f=9),1==W?d.firstChild.nodeValue=n[f]:"i"==r[0]||"I"==r[0]?(a=parseInt(a),isNaN(a)&&(a=0),1!=F&&(a*=F),d.firstChild.nodeValue=
t+" "+a+" "+u+A):"f"==r[0]||"F"==r[0]?(a=parseFloat(a),isNaN(a)&&(a=0),1!=F&&(a*=F),d.firstChild.nodeValue=t+" "+a.toFixed(I)+" "+u+A):d.firstChild.nodeValue=t+" "+a+" "+u+A):d.firstChild.nodeValue=t+" "+a+" "+u}var B=null,a=null,z=null,M,N,J,x,d,e,k,E,D,aa,ba,H,V,F,I,u,m=[],h=[],n=[],f,W,p=0,X,t,R,C,U,b,Y,L,v=1,r=[],A;this.registerplugin=function(b,d,e){B=b;a=e;a.registerattribute("ver","0");a.registerattribute("celltag","@[default]Tag 1");a.registerattribute("decimals","");a.registerattribute("stateind",
"0");a.registerattribute("mult","1.0");a.registerattribute("links","");a.registerattribute("bordercolour","0x000000");a.registerattribute("borderthickness","2");a.registerattribute("cellbackgroundcolour","0xFFFF00");a.registerattribute("fcolour","0xFF0000");a.registerattribute("xarrowcolour","0xFFFF00");a.registerattribute("fnt","5");a.registerattribute("fsiz","4");a.registerattribute("fbold","0");a.registerattribute("fitalic","0");a.registerattribute("fjust","1");a.registerattribute("opacity","1.0");
a.registerattribute("units","");a.registerattribute("description","");a.registerattribute("state0colour","0xFFFF00");a.registerattribute("state1colour","0xFFA500");a.registerattribute("state2colour","0xFF0000");a.registerattribute("state3colour","0x8A2BE2");a.registerattribute("state4colour","0x0000FF");a.registerattribute("state5colour","0xFFFF00");a.registerattribute("state6colour","0xFFA500");a.registerattribute("state7colour","0xFF0000");a.registerattribute("state8colour","0x8A2BE2");a.registerattribute("state9colour",
"0x0000FF");a.registerattribute("state0blink","0");a.registerattribute("state1blink","1");a.registerattribute("state2blink","2");a.registerattribute("state3blink","1");a.registerattribute("state4blink","2");a.registerattribute("state5blink","0");a.registerattribute("state6blink","1");a.registerattribute("state7blink","2");a.registerattribute("state8blink","1");a.registerattribute("state9blink","2");a.registerattribute("state0","state0");a.registerattribute("state1","state1");a.registerattribute("state2",
"state2");a.registerattribute("state3","state3");a.registerattribute("state4","state4");a.registerattribute("state5","state5");a.registerattribute("state6","state6");a.registerattribute("state7","state7");a.registerattribute("state8","state8");a.registerattribute("state9","state9");a.handcursor=!1;a.registercontentsize(100,100);z=document.createElementNS("http://www.w3.org/2000/svg","svg");z.style.width="100%";z.style.height="100%";a.sprite.appendChild(z);1==Number(a.ver)&&B.trace(1,"hello from plugin["+
a.name+"] version = 1.0");ca()};this.unloadplugin=function(){k.removeEventListener("click",K);k.removeEventListener("mouseover",O);k.removeEventListener("mouseout",P);b.removeEventListener("click",K);b.removeEventListener("mouseover",O);b.removeEventListener("mouseout",P);1==H&&(clearInterval(aa),clearInterval(ba));B=a=null};this.onresize=function(a,b){return!1}};
