var krpanoplugin=function(){function J(k){a.handcursor=!0}function P(a){H(0)}function K(k){a.handcursor=!1}function Q(a){H(1)}function O(){0!=L?(u=m.get("stagewidth"),v=m.get("stageheight"),a.width=u,a.height=v,d.setAttribute("visibility","visible"),l.setAttribute("visibility","visible"),c.setAttribute("visibility","visible"),n.setAttribute("visibility","visible"),p.setAttribute("visibility","visible"),q.setAttribute("visibility","visible"),r.setAttribute("visibility","visible"),L=0):(u=m.get("stagewidth"),
v=m.get("stageheight"),a.width=20,a.height=20,d.setAttribute("visibility","hidden"),l.setAttribute("visibility","hidden"),c.setAttribute("visibility","hidden"),n.setAttribute("visibility","hidden"),p.setAttribute("visibility","hidden"),q.setAttribute("visibility","hidden"),r.setAttribute("visibility","hidden"),L=1)}function H(a){var b,e,c,f,g,l,x;b=m.get("mouse.x");e=m.get("mouse.y");m.call("screentosphere(mouse.x, mouse.y, mouseath, mouseatv)");c=m.get("mouseath").toFixed(2);f=m.get("mouseatv").toFixed(2);
y="x= "+b+", y= "+e+", h= "+c+", v= "+f;z=b-u;A=e;B=b+u;C=e;D=b;E=e-v;F=b;G=e+v;0>z&&(z=0);0>A&&(A=0);B>u&&(B=u);C>v&&(C=v);0>D&&(D=0);0>E&&(E=0);F>u&&(F=u);G>v&&(G=v);n.setAttribute("x1",z);n.setAttribute("y1",A);n.setAttribute("x2",B);n.setAttribute("y2",C);p.setAttribute("x1",D);p.setAttribute("y1",E);p.setAttribute("x2",F);p.setAttribute("y2",G);1==a&&(a=z,b=A,e=B,c=C,f=D,g=E,l=F,x=G,q.setAttribute("x1",a),q.setAttribute("y1",b),q.setAttribute("x2",e),q.setAttribute("y2",c),r.setAttribute("x1",
f),r.setAttribute("y1",g),r.setAttribute("x2",l),r.setAttribute("y2",x),I=y,m.trace(1,"cross hair position="+y));d.firstChild.nodeValue=y+" : "+I}var m=null,a=null,f=null,R,y,d,l,c,g,L=0,n,p,q,r,z=0,A=0,B=0,C=0,D=0,E=0,F=0,G=0,u,v,I;this.registerplugin=function(k,b,e){m=k;a=e;a.registerattribute("ver","0");a.registerattribute("cellbackgroundcolour","0xFFFF00");a.registerattribute("fcolour","0xFF0000");a.registerattribute("fnt","5");a.registerattribute("fsiz","4");a.registerattribute("fbold","0");
a.registerattribute("fitalic","0");a.registerattribute("fjust","1");a.registerattribute("units","");a.handcursor=!1;a.registercontentsize(256,256);f=document.createElementNS("http://www.w3.org/2000/svg","svg");f.style.width="100%";f.style.height="100%";a.sprite.appendChild(f);1==Number(a.ver)&&m.trace(1,"hello from plugin["+a.name+"] version = 1.0");var t,M,w,N,x,H,h;a.cellbackgroundcolour=a.cellbackgroundcolour.replace(/0x/gi,"#");a.fcolour=a.fcolour.replace(/0x/gi,"#");y="                                                                    ";
I=a.units;b=k=0;5>k&&(k=5);5>b&&(b=5);R=a.cellbackgroundcolour;e=a.fcolour;w=parseInt(a.fnt);t=parseInt(a.fsiz);N=parseInt(a.fjust);x=parseInt(a.fbold);H=parseInt(a.fitalic);1==w?h="Times New Roman":2==w?h="Arial":3==w?h="Calibri":4==w?h="Sans-Serif":5==w?h="Verdana":6==w&&(h="Century");w=1==t?10:2==t?11:3==t?12:4==t?14:5==t?16:6==t?18:10;u=m.get("stagewidth");v=m.get("stageheight");a.width=u;a.height=v;t=y.length+I.length+1;1>t&&(t=1);t=Math.round(t*w*.65)+k;M=1.1*w+b;x=1==x?"bold":"normal";l=document.createElementNS("http://www.w3.org/2000/svg",
"rect");l.setAttribute("x",0);l.setAttribute("y",0);l.setAttribute("width",u);l.setAttribute("height",v);l.setAttribute("stroke-width",0);l.setAttribute("stroke",0);l.setAttribute("fill",R);l.setAttribute("fill-opacity",.1);c=document.createElementNS("http://www.w3.org/2000/svg","rect");c.setAttribute("x",0);c.setAttribute("y",0);c.setAttribute("width",u);c.setAttribute("height",v);c.setAttribute("fill-opacity",0);c.setAttribute("fill",0);d=document.createElementNS("http://www.w3.org/2000/svg","text");
0==N?(d.setAttribute("text-anchor","start"),d.setAttribute("x",0+k),d.setAttribute("y",0+M/2+b)):1==N?(d.setAttribute("text-anchor","middle"),d.setAttribute("x",0+t/2),d.setAttribute("y",0+M/2+b)):2==N&&(d.setAttribute("text-anchor","end"),d.setAttribute("x",0+t-k),d.setAttribute("y",0+M/2+b));1==H&&d.setAttribute("font-style","italic");d.setAttribute("font-size",w);d.setAttribute("font-family",h);d.setAttribute("fill",e);d.setAttribute("font-weight",x);h=document.createTextNode(y+I);d.appendChild(h);
d.setAttribute("visibility","visible");l.setAttribute("visibility","visible");c.setAttribute("visibility","visible");h=document.createElementNS("http://www.w3.org/2000/svg","rect");h.setAttribute("x",0);h.setAttribute("y",0);h.setAttribute("width",20);h.setAttribute("height",20);h.setAttribute("stroke-width",1);h.setAttribute("stroke","white");h.setAttribute("fill-opacity",1);h.setAttribute("fill",0);k=document.createElementNS("http://www.w3.org/2000/svg","line");k.setAttribute("x1",4);k.setAttribute("y1",
4);k.setAttribute("x2",16);k.setAttribute("y2",4);k.setAttribute("stroke-width",1);k.setAttribute("stroke","white");k.setAttribute("fill-opacity",1);b=document.createElementNS("http://www.w3.org/2000/svg","line");b.setAttribute("x1",16);b.setAttribute("y1",4);b.setAttribute("x2",10);b.setAttribute("y2",16);b.setAttribute("stroke-width",1);b.setAttribute("stroke","white");b.setAttribute("fill-opacity",1);e=document.createElementNS("http://www.w3.org/2000/svg","line");e.setAttribute("x1",10);e.setAttribute("y1",
16);e.setAttribute("x2",4);e.setAttribute("y2",4);e.setAttribute("stroke-width",1);e.setAttribute("stroke","white");e.setAttribute("fill-opacity",1);n=document.createElementNS("http://www.w3.org/2000/svg","line");n.setAttribute("x1",z);n.setAttribute("y1",A);n.setAttribute("x2",B);n.setAttribute("y2",C);n.setAttribute("stroke-width",1);n.setAttribute("stroke","white");n.setAttribute("fill-opacity",1);p=document.createElementNS("http://www.w3.org/2000/svg","line");p.setAttribute("x1",D);p.setAttribute("y1",
E);p.setAttribute("x2",F);p.setAttribute("y2",G);p.setAttribute("stroke-width",1);p.setAttribute("stroke","white");p.setAttribute("fill-opacity",1);q=document.createElementNS("http://www.w3.org/2000/svg","line");q.setAttribute("x1",z);q.setAttribute("y1",A);q.setAttribute("x2",B);q.setAttribute("y2",C);q.setAttribute("stroke-width",1);q.setAttribute("stroke","blue");q.setAttribute("fill-opacity",1);r=document.createElementNS("http://www.w3.org/2000/svg","line");r.setAttribute("x1",D);r.setAttribute("y1",
E);r.setAttribute("x2",F);r.setAttribute("y2",G);r.setAttribute("stroke-width",1);r.setAttribute("stroke","blue");r.setAttribute("fill-opacity",1);g=document.createElementNS("http://www.w3.org/2000/svg","rect");g.setAttribute("x",0);g.setAttribute("y",0);g.setAttribute("width",20);g.setAttribute("height",20);g.setAttribute("stroke-width",1);g.setAttribute("stroke",0);g.setAttribute("fill-opacity",0);g.setAttribute("fill",0);f.appendChild(n);f.appendChild(p);f.appendChild(q);f.appendChild(r);f.appendChild(l);
f.appendChild(d);f.appendChild(c);f.appendChild(h);f.appendChild(k);f.appendChild(b);f.appendChild(e);f.appendChild(g);c.addEventListener("click",Q);c.addEventListener("mouseover",J);c.addEventListener("mousemove",P);c.addEventListener("mouseout",K);g.addEventListener("click",O);g.addEventListener("mouseover",J);g.addEventListener("mouseout",K);L=0;O()};this.unloadplugin=function(){c.removeEventListener("click",Q);c.removeEventListener("mouseover",J);c.removeEventListener("mousemove",P);c.removeEventListener("mouseout",
K);g.removeEventListener("click",O);g.removeEventListener("mouseover",J);g.removeEventListener("mouseout",K);m=a=null};this.onresize=function(a,b){return!1}};
