var krpanoplugin=function(){function ia(e){a.handcursor=!0}function ja(e){a.handcursor=!1}function ka(){var e;if(0==P){P=1;for(e=0;2>e;e++)f[e].setAttribute("visibility","hidden");for(e=0;e<=n;e++)d[e].setAttribute("visibility","hidden");for(e=0;e<h+1;e++)k[e].setAttribute("visibility","hidden");l.setAttribute("visibility","hidden");a.registercontentsize(xarrowwidth,13);r.firstChild.nodeValue=a.name}else{for(e=P=0;2>e;e++)f[e].setAttribute("visibility","visible");for(e=0;e<=n;e++)d[e].setAttribute("visibility",
"visible");for(e=0;e<h+1;e++)k[e].setAttribute("visibility","visible");l.setAttribute("visibility","visible");r.setAttribute("fill-opacity",w);a.registercontentsize(Y,fa);r.firstChild.nodeValue=""}}function qa(){var e,J,N,p,g,C,O,da,S,F,T,b,m,Z,K,aa=[],ba=[],U=[],L=[];a.bordercolour=a.bordercolour.replace(/0x/gi,"#");a.fillcolour=a.fillcolour.replace(/0x/gi,"#");a.fcolour=a.fcolour.replace(/0x/gi,"#");a.vfcolour=a.vfcolour.replace(/0x/gi,"#");a.xarrowcolour=a.xarrowcolour.replace(/0x/gi,"#");a.needlecolour=
a.needlecolour.replace(/0x/gi,"#");a.state0colour=a.state0colour.replace(/0x/gi,"#");a.state1colour=a.state1colour.replace(/0x/gi,"#");a.state2colour=a.state2colour.replace(/0x/gi,"#");a.state3colour=a.state3colour.replace(/0x/gi,"#");a.state4colour=a.state4colour.replace(/0x/gi,"#");a.state5colour=a.state5colour.replace(/0x/gi,"#");a.state6colour=a.state6colour.replace(/0x/gi,"#");a.state7colour=a.state7colour.replace(/0x/gi,"#");a.state8colour=a.state8colour.replace(/0x/gi,"#");a.state9colour=a.state9colour.replace(/0x/gi,
"#");x[0]=a.state0colour;x[1]=a.state1colour;x[2]=a.state2colour;x[3]=a.state3colour;x[4]=a.state4colour;x[5]=a.state5colour;x[6]=a.state6colour;x[7]=a.state7colour;x[8]=a.state8colour;x[9]=a.state9colour;w=parseFloat(a.opacity);ea=.5*w;D[0]=parseInt(a.state0blink);D[1]=parseInt(a.state1blink);D[2]=parseInt(a.state2blink);D[3]=parseInt(a.state3blink);D[4]=parseInt(a.state4blink);D[5]=parseInt(a.state5blink);D[6]=parseInt(a.state6blink);D[7]=parseInt(a.state7blink);D[8]=parseInt(a.state8blink);D[9]=
parseInt(a.state9blink);e=a.bordercolour;J=parseInt(a.borderwidth);la=a.fillcolour;F=parseFloat(a.almin);T=parseFloat(a.almax);ga=a.metertag.replace("@"," ").trim();M=getattr(ga).split(",");q=0;u=parseFloat(a.minvalue);A=parseFloat(a.maxvalue);V=a.description;0==V.length&&(V=M[1]);W=a.units;0==W.length&&(W=M[2]);X=parseInt(a.decimals);0==X.length&&(X=M[4]);S=parseInt(a.decimalscale);ha=parseFloat(a.mult);c=parseInt(a.radius);N=a.vfcolour;p=parseInt(a.vfnt);g=parseInt(a.vfsiz);O=parseInt(a.vbold);
da=parseInt(a.vitalic);C=parseInt(a.vjust);p=1==p?"Times New Roman":2==p?"Arial":3==p?"Calibri":4==p?"Helvetica":5==p?"Verdana":6==p?"Century":"Arial";g=1==g?10:2==g?11:3==g?12:4==g?14:5==g?16:6==g?18:8;O=1==O?"bold":"normal";G=q.toFixed(X);m=parseInt(M[3]);0>=m&&(m=G.length);b=m+W.length+15;b<V.length&&(b=V.length);m=Math.round(b*g*.65);xarrowwidth=Math.round(a.name.length*g*.65);Z=1.1*g;ma=1==P?a.name:"";r=document.createElementNS("http://www.w3.org/2000/svg","text");r.setAttribute("x",0);r.setAttribute("y",
8);r.setAttribute("font-size",12);r.setAttribute("font-family","Arial");r.setAttribute("font-style","normal");r.setAttribute("fill",a.xarrowcolour);r.setAttribute("font-weight","bold");r.setAttribute("text-anchor","left");r.setAttribute("visibility","visible");var Q=document.createTextNode(ma);r.appendChild(Q);H.appendChild(r);B=0;v=m>2*c?m/2-c:0;K=[];Q=[];K[0]=v+c;Q[0]=2*c+Z;K[1]=v+c;Q[1]=Q[0]+Z;for(b=0;2>b;b++){f[b]=document.createElementNS("http://www.w3.org/2000/svg","text");f[b].setAttribute("x",
0);f[b].setAttribute("y",Q[b]);f[b].setAttribute("text-anchor","start");1==C?(f[b].setAttribute("x",K[b]),f[b].setAttribute("text-anchor","middle")):2==C&&(f[b].setAttribute("x",v+2*c),f[b].setAttribute("text-anchor","end"));1==da&&f[b].setAttribute("font-style","italic");f[b].setAttribute("font-size",g);f[b].setAttribute("font-family",p);f[b].setAttribute("fill",x[E]);1==b&&f[b].setAttribute("fill",N);f[b].setAttribute("font-weight",O);f[b].setAttribute("visibility","visible");var I;G=0==b?q.toFixed(X)+
" "+W:V;I=document.createTextNode(G);f[b].appendChild(I);H.appendChild(f[b])}N=a.fcolour;p=parseInt(a.fnt);g=parseInt(a.fsiz);C=parseInt(a.just);O=parseInt(a.bold);da=parseInt(a.italic);p=1==p?"Times New Roman":2==p?"Arial":3==p?"Calibri":4==p?"Sans-Serif":5==p?"Verdana":6==p?"Century":"Arial";g=1==g?10:2==g?11:3==g?12:4==g?14:5==g?16:6==g?18:10;O=1==O?"bold":"normal";G=A.toFixed(S);b=G.length;K=1.1*g;d[0]=document.createElementNS("http://www.w3.org/2000/svg","circle");d[0].setAttribute("cx",v+c);
d[0].setAttribute("cy",B+c);d[0].setAttribute("r",c);d[0].setAttribute("stroke-width",0);d[0].setAttribute("fill",la);d[0].setAttribute("stroke-opacity",w);d[0].setAttribute("fill-opacity",w);d[0].setAttribute("visibility","visible");d[1]=document.createElementNS("http://www.w3.org/2000/svg","circle");d[1].setAttribute("cx",v+c);d[1].setAttribute("cy",B+c);d[1].setAttribute("r",.9*c);d[1].setAttribute("stroke-width",J);d[1].setAttribute("stroke",e);d[1].setAttribute("fill","none");d[1].setAttribute("stroke-opacity",
w);d[1].setAttribute("fill-opacity",w);d[1].setAttribute("visibility","visible");h=parseInt(a.divisions);5>h&&(h=5);6<h&&(h=6);C=240/h;I=210;for(b=0;b<h+1;b++)aa[b]=v+c+c*Math.cos(I*y),ba[b]=B+c-c*Math.sin(I*y),U[b]=v+c+.8*c*Math.cos(I*y),L[b]=B+c-.8*c*Math.sin(I*y),I-=C;n=1;for(b=0;b<h+1;b++)n++,d[n]=document.createElementNS("http://www.w3.org/2000/svg","line"),d[n].setAttribute("x1",aa[b]),d[n].setAttribute("y1",ba[b]),d[n].setAttribute("x2",U[b]),d[n].setAttribute("y2",L[b]),d[n].setAttribute("stroke",
e),d[n].setAttribute("stroke-width",J),d[n].setAttribute("stroke-opacity",w),d[n].setAttribute("visibility","visible");b=h;F>u&&F<A&&(n++,b++,e=-30+(F-u)/(A-u)*240,aa[b]=v+c+c*Math.cos(e*y),ba[b]=B+c-c*Math.sin(e*y),U[b]=v+c+.8*c*Math.cos(e*y),L[b]=B+c-.8*c*Math.sin(e*y));T<A&&F>u&&(n++,b++,F=-30+(T-u)/(A-u)*240,aa[b]=v+c+c*Math.cos(F*y),ba[b]=B+c-c*Math.sin(F*y),U[b]=v+c+.8*c*Math.cos(F*y),L[b]=B+c-.8*c*Math.sin(F*y));if(n>h+2)for(b=h+3;b<n+1;b++)d[b]=document.createElementNS("http://www.w3.org/2000/svg",
"line"),d[b].setAttribute("x1",aa[b-2]),d[b].setAttribute("y1",ba[b-2]),d[b].setAttribute("x2",U[b-2]),d[b].setAttribute("y2",L[b-2]),d[b].setAttribute("stroke","#FF0000"),d[b].setAttribute("stroke-width",J),d[b].setAttribute("stroke-opacity",w),d[1].setAttribute("visibility","visible");for(b=0;b<=n;b++)H.appendChild(d[b]);t=(A-u)/h;for(b=0;b<h+1;b++)k[b]=document.createElementNS("http://www.w3.org/2000/svg","text"),C=0,b==h/2&&(C=1),b>h/2&&(C=2),k[b].setAttribute("x",U[b]),1==C?k[b].setAttribute("y",
L[b]+K):0==b||b==h?k[b].setAttribute("y",L[b]+.2*K):1==b||b==h-1?k[b].setAttribute("y",L[b]+.5*K):k[b].setAttribute("y",L[b]+.8*K),k[b].setAttribute("text-anchor","start"),1==C?k[b].setAttribute("text-anchor","middle"):2==C&&k[b].setAttribute("text-anchor","end"),1==da&&k[b].setAttribute("font-style","italic"),k[b].setAttribute("font-size",g),k[b].setAttribute("font-family",p),k[b].setAttribute("fill",N),k[b].setAttribute("font-weight",O),k[b].setAttribute("visibility","visible"),G=(u+b*t).toFixed(S),
I=document.createTextNode(G),k[b].appendChild(I),H.appendChild(k[b]);q<u&&(q=u);q>A&&(q=A);J=y*(210-240*(q-u)/(A-u));N=Math.sin(J);J=c+.8*c*Math.cos(J);N=c-.8*c*N;l=document.createElementNS("http://www.w3.org/2000/svg","line");l.setAttribute("x1",v+J);l.setAttribute("y1",B+N);l.setAttribute("x2",v+c);l.setAttribute("y2",B+c);l.setAttribute("stroke",x[E]);l.setAttribute("stroke-width",3);l.setAttribute("stroke-linecap","round");l.setAttribute("stroke-opacity",w);l.setAttribute("visibility","visible");
H.appendChild(l);Y=2*c;m>Y&&(Y=m);fa=Q[0]+Z+10;z=document.createElementNS("http://www.w3.org/2000/svg","rect");z.setAttribute("x",0);z.setAttribute("y",0);z.setAttribute("width",v+2*c);z.setAttribute("height",B+2*c+Z);z.setAttribute("fill-opacity",0);z.setAttribute("fill",0);H.appendChild(z);1==P?a.registercontentsize(xarrowwidth,13):a.registercontentsize(Y,fa);z.addEventListener("click",ka);z.addEventListener("mouseover",ia);z.addEventListener("mouseout",ja);m=getcycletime();m=m.trim();m=parseInt(m);
isNaN(m)?m=5:0>=m&&(m=5);setTimeout(na,1E3);oa=setInterval(function(){na()},1E3*m);pa=setInterval(function(){ra||mack_status()?ca(1):(1==D[E]?2==R||3==R?ca(0):ca(1):2==D[E]&&(1==R||3==R?ca(0):ca(1)),R++,3<R&&(R=0))},500)}function na(a){a=somefunction(ga).split(",");S="";q="i"==M[0]||"I"==M[0]?parseInt(a[0]):"f"==M[0]||"F"==M[0]?parseFloat(a[0]):0;isNaN(q)&&(q=0);1<a.length?(E=parseInt(a[1]),isNaN(E)&&(E=0),2<a.length&&(S=a[2])):E=0;1!=ha&&(q*=ha);q<u&&(q=u);q>A&&(q=A);G=q.toFixed(X)+" "+W+S;f[0].firstChild.nodeValue=
G;var d;a=y*(210-240*(q-u)/(A-u));d=Math.sin(a);a=v+c+.8*c*Math.cos(a);d=B+c-.8*c*d;l.setAttribute("x1",a);l.setAttribute("y1",d);l.setAttribute("stroke",x[E]);f[0].setAttribute("fill",x[E])}function ca(a){1==a?(0<E&&1==P&&r.setAttribute("fill-opacity",w),l.setAttribute("visibility","visible"),f[0].setAttribute("visibility","visible"),l.setAttribute("stroke-opacity",w),f[0].setAttribute("fill-opacity",w)):(0<E&&1==P&&r.setAttribute("fill-opacity",ea),l.setAttribute("stroke-opacity",ea),f[0].setAttribute("fill-opacity",
ea))}var T=null,a=null,H=null,G,z,ga,q,u,A,oa,pa,W,V,X,ha,la,l,c,f=[],x=[],D=[],E=0,R=0,y=3.14159/180,ra,v,B,w,ea=.5*w,ma,r,d=[],k=[],n,h,P=1,Y,fa,M=[],S;this.registerplugin=function(c,d,f){T=c;a=f;a.registerattribute("ver","0");a.registerattribute("fillcolour","0x777777");a.registerattribute("needlecolour","0xFF0000");a.registerattribute("radius","50");a.registerattribute("bordercolour","0xffffff");a.registerattribute("borderwidth","2");a.registerattribute("fcolour","0x0000ff");a.registerattribute("xarrowcolour",
"0xffff00");a.registerattribute("fnt","2");a.registerattribute("fsiz","1");a.registerattribute("italic","0");a.registerattribute("bold","0");a.registerattribute("just","1");a.registerattribute("vfcolour","0xFF0000");a.registerattribute("vfnt","5");a.registerattribute("vfsiz","2");a.registerattribute("vitalic","0");a.registerattribute("vbold","1");a.registerattribute("vjust","1");a.registerattribute("metertag","[default]Tag 0");a.registerattribute("maxvalue","100");a.registerattribute("minvalue","0");
a.registerattribute("almin","15");a.registerattribute("almax","85");a.registerattribute("units","");a.registerattribute("description","");a.registerattribute("decimals","");a.registerattribute("decimalscale","0");a.registerattribute("mult","1.0");a.registerattribute("opacity","1.0");a.registerattribute("divisions","5");a.registerattribute("state0colour","0xFFFF00");a.registerattribute("state1colour","0xFFA500");a.registerattribute("state2colour","0xFF0000");a.registerattribute("state3colour","0x8A2BE2");
a.registerattribute("state4colour","0x0000FF");a.registerattribute("state5colour","0xFFFF00");a.registerattribute("state6colour","0xFFA500");a.registerattribute("state7colour","0xFF0000");a.registerattribute("state8colour","0x8A2BE2");a.registerattribute("state9colour","0x0000FF");a.registerattribute("state0blink","0");a.registerattribute("state1blink","1");a.registerattribute("state2blink","2");a.registerattribute("state3blink","1");a.registerattribute("state4blink","2");a.registerattribute("state5blink",
"0");a.registerattribute("state6blink","1");a.registerattribute("state7blink","2");a.registerattribute("state8blink","1");a.registerattribute("state9blink","2");a.handcursor=!1;a.registercontentsize(100,100);H=document.createElementNS("http://www.w3.org/2000/svg","svg");H.style.width="100%";H.style.height="100%";a.sprite.appendChild(H);1==parseInt(a.ver)&&T.trace(1,"hello from plugin["+a.name+"] version =1.0");qa()};this.unloadplugin=function(){z.removeEventListener("click",ka);z.removeEventListener("mouseover",
ia);z.removeEventListener("mouseout",ja);clearInterval(oa);clearInterval(pa);T=a=null}};
