var krpanoplugin=function(){function I(h){a.handcursor=!0}function J(h){a.handcursor=!1}function K(){0==t?(t=1,b.setAttribute("visibility","hidden"),c.setAttribute("visibility","hidden"),f.firstChild.nodeValue=a.name,a.registercontentsize(D,15)):(t=0,b.setAttribute("visibility","visible"),c.setAttribute("visibility","visible"),f.firstChild.nodeValue="",a.registercontentsize(E,F))}function T(){var h,d,u=[],q,e,x,B,L,y,G,M;a.bordercolour=a.bordercolour.replace(/0x/gi,"#");a.cellbackgroundcolour=a.cellbackgroundcolour.replace(/0x/gi,
"#");a.fcolour=a.fcolour.replace(/0x/gi,"#");a.xarrowcolour=a.xarrowcolour.replace(/0x/gi,"#");a.state0colour=a.state0colour.replace(/0x/gi,"#");a.state1colour=a.state1colour.replace(/0x/gi,"#");a.state2colour=a.state2colour.replace(/0x/gi,"#");a.state3colour=a.state3colour.replace(/0x/gi,"#");a.state4colour=a.state4colour.replace(/0x/gi,"#");a.state5colour=a.state5colour.replace(/0x/gi,"#");a.state6colour=a.state6colour.replace(/0x/gi,"#");a.state7colour=a.state7colour.replace(/0x/gi,"#");a.state8colour=
a.state8colour.replace(/0x/gi,"#");a.state9colour=a.state9colour.replace(/0x/gi,"#");m[0]=a.state0colour;m[1]=a.state1colour;m[2]=a.state2colour;m[3]=a.state3colour;m[4]=a.state4colour;m[5]=a.state5colour;m[6]=a.state6colour;m[7]=a.state7colour;m[8]=a.state8colour;m[9]=a.state9colour;n[0]=parseInt(a.state0blink);n[1]=parseInt(a.state1blink);n[2]=parseInt(a.state2blink);n[3]=parseInt(a.state3blink);n[4]=parseInt(a.state4blink);n[5]=parseInt(a.state5blink);n[6]=parseInt(a.state6blink);n[7]=parseInt(a.state7blink);
n[8]=parseInt(a.state8blink);n[9]=parseInt(a.state9blink);H=parseFloat(a.opacity);d=0;l=a.msitag.replace("@","").trim();N=getattr(l).split(",");q=a.bordercolour;e=parseInt(a.borderthickness);1>e&&(e=1);5<e&&(e=5);z=a.cellbackgroundcolour;x=a.fcolour;h=parseInt(a.fnt);d=parseInt(a.fsiz);B=parseInt(a.fjust);L=parseInt(a.fbold);M=parseInt(a.fitalic);C="";k=0;O=!1;A=0;u.length=0;u=l.split(":");1<u.length&&(C=u[1].trim());l=u[0];0<l.length&&(l=l.trim(),"@"==l.charAt(0)?(A=1,""==C&&(C=" "),l.split("|")):
A=1);u=1==h?"Times New Roman":2==h?"Arial":3==h?"Calibri":4==h?"Sans-Serif":5==h?"Verdana":6==h?"Century":"Arial";y=1==d?10:2==d?11:3==d?12:4==d?14:5==d?16:6==d?18:10;G="normal";v=w=e;d=parseInt(N[3]);1>d&&(d=1);h=Math.round((d+4)*y*.65);D=Math.round(a.name.length*y*.65);d=1.5*y;G=1==L?"bold":"normal";c=document.createElementNS("http://www.w3.org/2000/svg","rect");c.setAttribute("x",w);c.setAttribute("y",v);c.setAttribute("width",h);c.setAttribute("height",d);c.setAttribute("stroke-width",e);c.setAttribute("stroke",
q);c.setAttribute("fill",z);c.setAttribute("stroke-opacity",H);c.setAttribute("fill-opacity",H);g=document.createElementNS("http://www.w3.org/2000/svg","rect");g.setAttribute("x",w);g.setAttribute("y",v);g.setAttribute("width",h);g.setAttribute("height",d);g.setAttribute("fill-opacity",0);g.setAttribute("stroke-opacity",0);g.setAttribute("fill",0);b=document.createElementNS("http://www.w3.org/2000/svg","text");0==B?(b.setAttribute("text-anchor","start"),b.setAttribute("x",w),b.setAttribute("y",v+
.75*d)):1==B?(b.setAttribute("text-anchor","middle"),b.setAttribute("x",w+h/2),b.setAttribute("y",v+.75*d)):2==B&&(b.setAttribute("text-anchor","end"),b.setAttribute("x",w+h),b.setAttribute("y",v+.75*d));1==M&&b.setAttribute("font-style","italic");b.setAttribute("font-size",y);b.setAttribute("font-family",u);b.setAttribute("fill",x);b.setAttribute("font-weight",G);q=document.createTextNode(" ");0!=A&&(l=l.replace("@",""),l=l.trim());b.appendChild(q);0==t?(b.setAttribute("visibility","visible"),c.setAttribute("visibility",
"visible")):(b.setAttribute("visibility","hidden"),c.setAttribute("visibility","hidden"));g.setAttribute("visibility","visible");E=h+2*e;F=d+2*e;0==t?a.registercontentsize(E,F):a.registercontentsize(D,15);r.appendChild(c);r.appendChild(b);r.appendChild(g);P=0==t?"":a.name;f=document.createElementNS("http://www.w3.org/2000/svg","text");f.setAttribute("x",0);f.setAttribute("y",10);f.setAttribute("font-size",12);f.setAttribute("font-family","Arial");f.setAttribute("font-style","normal");f.setAttribute("fill",
a.xarrowcolour);f.setAttribute("font-weight","bold");f.setAttribute("text-anchor","left");f.setAttribute("visibility","visible");f.setAttribute("fill-opacity",1);e=document.createTextNode(P);f.appendChild(e);r.appendChild(f);r.appendChild(g);g.addEventListener("click",K);g.addEventListener("mouseover",I);g.addEventListener("mouseout",J);e=getcycletime();e=e.trim();e=parseInt(e);isNaN(e)?e=1:0>=e&&(e=1);setTimeout(Q,1E3);R=setInterval(function(){Q()},1E3*e);S=setInterval(function(){1==t?0<k?(1==p||
3==p?f.setAttribute("fill-opacity","1.0"):f.setAttribute("fill-opacity","0.5"),p++,3<p&&(p=0)):f.setAttribute("fill-opacity","1.0"):O||mack_status()?(c.setAttribute("fill",m[k]),p=0):(0==n[k]?c.setAttribute("fill",z):1==n[k]?2==p||3==p?c.setAttribute("fill",z):c.setAttribute("fill",m[k]):2==n[k]&&(1==p||3==p?c.setAttribute("fill",z):c.setAttribute("fill",m[k])),p++,3<p&&(p=0))},500)}function Q(){var a=[],d;x="";d=somefunction(l);a.length=0;a=d.split(",");k=1<a.length?parseInt(a[1]):0;9<k&&(q.trace(1,
"state out of range="+k),k=9);0>k&&(q.trace(1,"state out of range="+k),k=0);2<a.length&&(x=a[2]);b.firstChild.nodeValue=x}var q=null,a=null,r=null,E,F,z,l=[],b,c,g,w,v,C,R,S,A,n=[],m=[],k,p=0,O,H,f,P,D,t=1,N=[],x;this.registerplugin=function(b,d,c){q=b;a=c;a.registerattribute("ver","0");a.registerattribute("msitag","[default]Tag 101");a.registerattribute("bordercolour","0x000000");a.registerattribute("borderthickness","2");a.registerattribute("cellbackgroundcolour","0xFFFF00");a.registerattribute("fcolour",
"0xFF0000");a.registerattribute("xarrowcolour","0xFFFF00");a.registerattribute("fnt","5");a.registerattribute("fsiz","2");a.registerattribute("fbold","0");a.registerattribute("fitalic","0");a.registerattribute("fjust","1");a.registerattribute("opacity","1.0");a.registerattribute("state0colour","0xFFFF00");a.registerattribute("state1colour","0xFFA500");a.registerattribute("state2colour","0xFF0000");a.registerattribute("state3colour","0x8A2BE2");a.registerattribute("state4colour","0x0000FF");a.registerattribute("state5colour",
"0xFFFF00");a.registerattribute("state6colour","0xFFA500");a.registerattribute("state7colour","0xFF0000");a.registerattribute("state8colour","0x8A2BE2");a.registerattribute("state9colour","0x0000FF");a.registerattribute("state0blink","0");a.registerattribute("state1blink","1");a.registerattribute("state2blink","2");a.registerattribute("state3blink","1");a.registerattribute("state4blink","2");a.registerattribute("state5blink","0");a.registerattribute("state6blink","1");a.registerattribute("state7blink",
"2");a.registerattribute("state8blink","1");a.registerattribute("state9blink","2");a.registerattribute("state0label","state0");a.registerattribute("state1label","state1");a.registerattribute("state2label","state2");a.registerattribute("state3label","state3");a.registerattribute("state4label","state4");a.registerattribute("state5label","state5");a.registerattribute("state6label","state6");a.registerattribute("state7label","state7");a.registerattribute("state8label","state8");a.registerattribute("state9label",
"state9");a.handcursor=!1;a.registercontentsize(100,100);r=document.createElementNS("http://www.w3.org/2000/svg","svg");r.style.width="100%";r.style.height="100%";a.sprite.appendChild(r);1==Number(a.ver)&&q.trace(1,"hello from plugin["+a.name+"] version = 1.0");a.msitag=a.msitag.replace("\n","");a.msitag=a.msitag.replace("\r","");a.msitag=a.msitag.replace("\t","");T()};this.unloadplugin=function(){g.removeEventListener("click",K);g.removeEventListener("mouseover",I);g.removeEventListener("mouseout",
J);1==A&&(clearInterval(R),clearInterval(S));q=a=null};this.onresize=function(a,b){return!1}};
