var krpanoplugin=function(){function R(){var e;if(0==F){F=1;for(e=0;e<p;e++)l[e].setAttribute("visibility","hidden"),g[e].setAttribute("visibility","hidden");n.firstChild.nodeValue=a.name;a.registercontentsize(S,15)}else{for(e=F=0;e<p;e++)l[e].setAttribute("visibility","visible"),g[e].setAttribute("visibility","visible");n.firstChild.nodeValue="";a.registercontentsize(N,O)}}function T(e){a.handcursor=!0}function U(e){a.handcursor=!1}function ga(){var e=[],d,m=[],f=[],c=[],q=[],q=[],k,b,G,C,E,x,y,
H,v;a.colword=a.colword.replace(/0x/gi,"#");a.bordercolour=a.bordercolour.replace(/0x/gi,"#");a.cellbackgroundcolour=a.cellbackgroundcolour.replace(/0x/gi,"#");a.fcolour=a.fcolour.replace(/0x/gi,"#");a.xarrowcolour=a.xarrowcolour.replace(/0x/gi,"#");a.state0colour=a.state0colour.replace(/0x/gi,"#");a.state1colour=a.state1colour.replace(/0x/gi,"#");a.state2colour=a.state2colour.replace(/0x/gi,"#");a.state3colour=a.state3colour.replace(/0x/gi,"#");a.state4colour=a.state4colour.replace(/0x/gi,"#");a.state5colour=
a.state5colour.replace(/0x/gi,"#");a.state6colour=a.state6colour.replace(/0x/gi,"#");a.state7colour=a.state7colour.replace(/0x/gi,"#");a.state8colour=a.state8colour.replace(/0x/gi,"#");a.state9colour=a.state9colour.replace(/0x/gi,"#");t[0]=a.state0colour;t[1]=a.state1colour;t[2]=a.state2colour;t[3]=a.state3colour;t[4]=a.state4colour;t[5]=a.state5colour;t[6]=a.state6colour;t[7]=a.state7colour;t[8]=a.state8colour;t[9]=a.state9colour;w[0]=parseInt(a.state0blink);w[1]=parseInt(a.state1blink);w[2]=parseInt(a.state2blink);
w[3]=parseInt(a.state3blink);w[4]=parseInt(a.state4blink);w[5]=parseInt(a.state5blink);w[6]=parseInt(a.state6blink);w[7]=parseInt(a.state7blink);w[8]=parseInt(a.state8blink);w[9]=parseInt(a.state9blink);L=parseFloat(a.opacity);ba=.5*L;d=a.rowtag;z=getattr(d).split(",");d=d+";"+z[1]+";"+z[2]+";@"+d;h.length=0;h=d.split(";");k=h.length;""==h[k-1]&&(h.length=k-1);p=parseInt(a.columns);1>p&&(p=1);p=4;d=m.length=0;f=a.colword.split(":");C=G=5;5>G&&(G=5);5>C&&(C=5);E=a.bordercolour;x=parseInt(a.borderthickness);
1>x&&(x=1);5<x&&(x=5);P=a.cellbackgroundcolour;y=a.fcolour;H=parseInt(a.fnt);v=parseInt(a.fsiz);k=h.length;q=p;k>q&&(k=q,h.length=q);for(b=0;b<k;b++)M[b]="",V[b]=!1,r[b]=0;for(b=0;b<k;b++)if(q=h[b].split(":"),1<q.length&&(M[b]=q[1].trim()),h[b]=q[0],A[b]=0,0<h[b].length){for(ii=0;ii<h[b].length;ii++)if(" "!=h[b].charAt(ii)){A[b]=1;break}1==A[b]&&"@"==h[b].charAt(ii)?(W=A[b]=1,""==M[b]&&(M[b]=" "),q=h[b].split("|"),h[b]=q[0],I[b]=1,Q[b]=parseInt(z[4])):(A[b]=0,I[b]=1,Q[b]=0)}if(k<p)for(b=k;b<p;b++)h[b]=
" ",M[b]="",A[b]=0,I[b]=1,Q[b]=0,r[b]=0,V[b]=!1;var m=[],q=[],X=[],Y=[],Z=[];for(b=0;b<p;b++)q[b]=0,X[b]=0,Y[b]=0,Z[b]=0;if(0<f.length)for(b=0;b<f.length;b++)m=f[b].split(","),0<m.length&&(q[b]=parseInt(m[0]),1<m.length&&(X[b]=parseInt(m[1])),2<m.length&&(Y[b]=parseInt(m[2])),3<m.length&&(Z[b]=m[3]));k=p;m=1==H?"Times New Roman":2==H?"Arial":3==H?"Calibri":4==H?"Sans-Serif":5==H?"Verdana":6==H?"Century":"Arial";v=1==v?10:2==v?11:3==v?12:4==v?14:5==v?16:6==v?18:10;k=y;b="normal";J[0]=x;K[0]=x;for(f=
y=0;f<p;f++){c[f]=0;k=h[f];for(b=0;b<k.length&&" "==k.charAt(b);b++);b<k.length&&"@"==k.charAt(b)?c[f]=parseInt(z[3])+10:c[f]=k.length+1;e[f]=Math.round(c[f]*v*.65)+G;J[f+1]=J[f]+e[f]}0==d&&(d=1.1*v+C);S=Math.round(a.name.length*v*.65);K[1]=d;for(f=0;f<p;f++)c=f,b=1==X[f]?"bold":"normal",k=Z[f],l[c]=document.createElementNS("http://www.w3.org/2000/svg","rect"),l[c].setAttribute("x",J[f]),l[c].setAttribute("y",K[0]),l[c].setAttribute("width",e[f]),l[c].setAttribute("height",d),l[c].setAttribute("stroke-width",
x),l[c].setAttribute("stroke",E),l[c].setAttribute("fill",P),l[c].setAttribute("fill-opacity",L),l[c].setAttribute("stroke-opacity",L),g[c]=document.createElementNS("http://www.w3.org/2000/svg","text"),0==q[f]?(g[c].setAttribute("text-anchor","start"),g[c].setAttribute("x",J[f]+G),g[c].setAttribute("y",K[0]+d/2+C)):1==q[f]?(g[c].setAttribute("text-anchor","middle"),g[c].setAttribute("x",J[f]+e[f]/2),g[c].setAttribute("y",K[0]+d/2+C)):2==q[f]&&(g[c].setAttribute("text-anchor","end"),g[c].setAttribute("x",
J[f]+e[f]-G),g[c].setAttribute("y",K[0]+d/2+C)),1==Y[f]&&g[c].setAttribute("font-style","italic"),g[c].setAttribute("font-size",v),g[c].setAttribute("font-family",m),g[c].setAttribute("fill",k),g[c].setAttribute("font-weight",b),k=1==A[c]?document.createTextNode(" "):document.createTextNode(h[c]),0!=A[c]&&(h[c]=h[c].replace("@",""),h[c]=h[c].trim()),g[c].appendChild(k),0==F?(g[c].setAttribute("visibility","visible"),l[c].setAttribute("visibility","visible")):(g[c].setAttribute("visibility","hidden"),
l[c].setAttribute("visibility","hidden"));for(b=0;b<p;b++)y+=e[b];N=y+2*x+G;O=d+2*x+C;1==F?a.registercontentsize(S,15):a.registercontentsize(N,O);for(b=0;b<p;b++)D.appendChild(l[b]),D.appendChild(g[b]);u=document.createElementNS("http://www.w3.org/2000/svg","rect");u.setAttribute("x",0);u.setAttribute("y",0);u.setAttribute("width",N);u.setAttribute("height",O);u.setAttribute("fill-opacity",0);u.setAttribute("fill",0);ca=1==F?a.name:"";n=document.createElementNS("http://www.w3.org/2000/svg","text");
n.setAttribute("x",x);n.setAttribute("y",10);n.setAttribute("font-size",12);n.setAttribute("font-family","Arial");n.setAttribute("font-style","normal");n.setAttribute("fill",a.xarrowcolour);n.setAttribute("font-weight","bold");n.setAttribute("text-anchor","left");n.setAttribute("visibility","visible");e=document.createTextNode(ca);n.appendChild(e);u.addEventListener("click",R);u.addEventListener("mouseover",T);u.addEventListener("mouseout",U);D.appendChild(n);D.appendChild(u);1==W&&(e=getcycletime(),
e=e.trim(),e=parseInt(e),isNaN(e)?e=5:0>=e&&(e=5),setTimeout(da,1E3),ea=setInterval(function(){da()},1E3*e),fa=setInterval(function(){var a,b;b=mack_status();1==F&&(0<aa&&(0==B||2==B)?n.setAttribute("fill-opacity",ba):n.setAttribute("fill-opacity",L));for(a=0;a<p;a++)V[a]||b?l[a].setAttribute("fill",t[r[a]]):1==w[r[a]]?2==B||3==B?l[a].setAttribute("fill",P):l[a].setAttribute("fill",t[r[a]]):2==w[r[a]]?1==B||3==B?l[a].setAttribute("fill",P):l[a].setAttribute("fill",t[r[a]]):l[a].setAttribute("fill",
t[r[a]]);B++;3<B&&(B=0)},500))}function da(){var a,d,m;for(d=aa=0;d<p;d++)1==A[d]?(a=somefunction(h[d]),m=a.split(","),E="",a=m[0],r[d]=1<m.length?parseInt(m[1]):0,9<r[d]&&(y.trace(1,"state > 9:"+r[d]),r[d]=9),0>r[d]&&(y.trace(1,"state < 0:"+r[d]),r[d]=0),0<r[d]&&(aa=1),2<m.length&&(E=m[2]),"i"==z[0]||"I"==z[0]?(a=parseInt(a),isNaN(a)&&(a=0),1!=I[d]&&(a*=I[d]),g[d].firstChild.nodeValue=a+E):"f"==z[0]||"F"==z[0]?(a=parseFloat(a),isNaN(a)&&(a=0),1!=I[d]&&(a*=I[d]),g[d].firstChild.nodeValue=a.toFixed(Q[d])+
E):g[d].firstChild.nodeValue=a+E):g[d].firstChild.nodeValue=h[d]}var y=null,a=null,D=null,N,O,p,h=[],g=[],l=[],u,J=[],K=[],M=[],ea,fa,W,A=[],I=[],Q=[],P,w=[],t=[],r=[],B=0,V=[],L,ba,n,ca,S,F=1,aa=0,z=[],E;this.registerplugin=function(e,d,g){y=e;a=g;a.registerattribute("ver","0");a.registerattribute("rowtag","[default]Tag 102");a.registerattribute("colword","1,1,0,0x000000:0:2,1,1,0x000000:0");a.registerattribute("columns","4");a.registerattribute("bordercolour","0x000000");a.registerattribute("borderthickness",
"2");a.registerattribute("cellbackgroundcolour","0xFFFF00");a.registerattribute("fcolour","0xFF0000");a.registerattribute("xarrowcolour","0xFFFF00");a.registerattribute("fnt","4");a.registerattribute("fsiz","2");a.registerattribute("opacity","1.0");a.registerattribute("state0colour","0xFFFF00");a.registerattribute("state1colour","0xFFA500");a.registerattribute("state2colour","0xFF0000");a.registerattribute("state3colour","0x8A2BE2");a.registerattribute("state4colour","0x0000FF");a.registerattribute("state5colour",
"0xFFFF00");a.registerattribute("state6colour","0xFFA500");a.registerattribute("state7colour","0xFF0000");a.registerattribute("state8colour","0x8A2BE2");a.registerattribute("state9colour","0x0000FF");a.registerattribute("state0blink","0");a.registerattribute("state1blink","1");a.registerattribute("state2blink","2");a.registerattribute("state3blink","1");a.registerattribute("state4blink","2");a.registerattribute("state5blink","0");a.registerattribute("state6blink","1");a.registerattribute("state7blink",
"2");a.registerattribute("state8blink","1");a.registerattribute("state9blink","2");a.registerattribute("state0","state0");a.registerattribute("state1","state1");a.registerattribute("state2","state2");a.registerattribute("state3","state3");a.registerattribute("state4","state4");a.registerattribute("state5","state5");a.registerattribute("state6","state6");a.registerattribute("state7","state7");a.registerattribute("state8","state8");a.registerattribute("state9","state9");a.handcursor=!1;a.registercontentsize(512,
512);D=document.createElementNS("http://www.w3.org/2000/svg","svg");D.style.width="100%";D.style.height="100%";a.sprite.appendChild(D);1==Number(a.ver)&&y.trace(1,"hello from plugin["+a.name+"] version = 1.0");ga()};this.unloadplugin=function(){u.removeEventListener("click",R);u.removeEventListener("mouseover",T);u.removeEventListener("mouseout",U);n.removeEventListener("click",R);n.removeEventListener("mouseover",T);n.removeEventListener("mouseout",U);1==W&&(clearInterval(ea),clearInterval(fa));
y=a=null};this.onresize=function(a,d){return!1}};
