var krpanoplugin=function(){function ha(c){a.handcursor=!0}function ia(c){a.handcursor=!1}function ja(){var c;if(0==N){N=1;for(c=0;c<=k;c++)e[c].setAttribute("visibility","hidden");for(c=0;3>c;c++)d[c].setAttribute("visibility","hidden");for(c=0;c<ca;c++)n[c].setAttribute("visibility","hidden");for(c=0;2>c;c++)g[c].setAttribute("visibility","hidden");a.registercontentsize(da,15);t.firstChild.nodeValue=a.name}else{for(c=N=0;c<=k;c++)e[c].setAttribute("visibility","visible");for(c=0;3>c;c++)d[c].setAttribute("visibility",
"visible");for(c=0;c<ca;c++)n[c].setAttribute("visibility","visible");for(c=0;2>c;c++)g[c].setAttribute("visibility","visible");t.setAttribute("fill-opacity",E);a.registercontentsize(V,Z);t.firstChild.nodeValue=""}}function oa(){var c,u,Q,q,r,l,K,L,aa,O,z;a.scalecolour=a.scalecolour.replace(/0x/gi,"#");a.fcolour=a.fcolour.replace(/0x/gi,"#");a.vfcolour=a.vfcolour.replace(/0x/gi,"#");a.xarrowcolour=a.xarrowcolour.replace(/0x/gi,"#");a.state0colour=a.state0colour.replace(/0x/gi,"#");a.state1colour=
a.state1colour.replace(/0x/gi,"#");a.state2colour=a.state2colour.replace(/0x/gi,"#");a.state3colour=a.state3colour.replace(/0x/gi,"#");a.state4colour=a.state4colour.replace(/0x/gi,"#");a.state5colour=a.state5colour.replace(/0x/gi,"#");a.state6colour=a.state6colour.replace(/0x/gi,"#");a.state7colour=a.state7colour.replace(/0x/gi,"#");a.state8colour=a.state8colour.replace(/0x/gi,"#");a.state9colour=a.state9colour.replace(/0x/gi,"#");v[0]=a.state0colour;v[1]=a.state1colour;v[2]=a.state2colour;v[3]=a.state3colour;
v[4]=a.state4colour;v[5]=a.state5colour;v[6]=a.state6colour;v[7]=a.state7colour;v[8]=a.state8colour;v[9]=a.state9colour;F[0]=parseInt(a.state0blink);F[1]=parseInt(a.state1blink);F[2]=parseInt(a.state2blink);F[3]=parseInt(a.state3blink);F[4]=parseInt(a.state4blink);F[5]=parseInt(a.state5blink);F[6]=parseInt(a.state6blink);F[7]=parseInt(a.state7blink);F[8]=parseInt(a.state8blink);F[9]=parseInt(a.state9blink);E=parseFloat(a.opacity);ba=.5*E;c=a.scalecolour;u=parseInt(a.scalethick);1>u&&(u=1);Q=a.fcolour;
q=parseInt(a.fnt);r=parseInt(a.fsiz);K=parseInt(a.just);L=parseInt(a.bold);aa=parseInt(a.italic);q=1==q?"Times New Roman":2==q?"Arial":3==q?"Calibri":4==q?"Sans-Serif":5==q?"Verdana":6==q?"Century":"Arial";r=1==r?10:2==r?11:3==r?12:4==r?14:5==r?16:6==r?18:8;L=1==L?"bold":"normal";h=parseInt(a.barwidth);G=parseInt(a.barheight);ea=a.scaletag.replace("@"," ").trim();I=getattr(ea).split(",");R=a.description;0==R.length&&(R=I[1]);S=a.units;0==S.length&&(S=I[2]);w=0;x=parseFloat(a.minvalue);A=parseFloat(a.maxvalue);
W=parseInt(a.decimals);0==W.length&&(W=I[4]);fa=parseFloat(a.mult);z=parseInt(a.decimalscale);X=w.toFixed(W);l=parseInt(a.vfsiz);O=1==l?10:2==l?11:3==l?12:4==l?14:5==l?16:6==l?18:8;l=parseInt(I[3]);0>=l&&(l=X.length);l=l+S.length+15;l<R.length&&(l=R.length);1>l&&(l=1);l=Math.round(l*O*.65);da=Math.round(a.name.length*O*.65);O*=1.1;p=5;l>h+B?(V=l,m=(l-h-B)/2):(V=h+5+B,m=0);Z=G+p+2*O+10;var C,f,U;C=h/2;f=h/4;U=G/20;J[0]=h+m-C;T[0]=p;var b;for(b=1;21>b;b++)T[b]=T[b-1]+U,J[b]=h+m-f;J[5]=h+m-C;J[10]=h+
m-C;J[15]=h+m-C;J[20]=h+m-C;for(b=0;21>b;b++)e[b]=document.createElementNS("http://www.w3.org/2000/svg","line"),e[b].setAttribute("x1",J[b]),e[b].setAttribute("y1",T[b]),e[b].setAttribute("x2",h+m),e[b].setAttribute("y2",T[b]),e[b].setAttribute("stroke",c),e[b].setAttribute("stroke-width",u),e[b].setAttribute("stroke-opacity",E),e[b].setAttribute("visibility","visible");C=parseFloat(a.almin);b=parseFloat(a.almax);c=-1;k=20;C>x&&C<A&&(k++,f=(C-x)/(A-x)*G,c=G-f+p,e[k]=document.createElementNS("http://www.w3.org/2000/svg",
"line"),e[k].setAttribute("x1",J[0]),e[k].setAttribute("y1",c),e[k].setAttribute("x2",h+m),e[k].setAttribute("y2",c),e[k].setAttribute("stroke","#FF0000"),e[k].setAttribute("stroke-width",u),e[k].setAttribute("stroke-opacity",E),e[k].setAttribute("visibility","visible"));C=-1;b>x&&b<A&&(k++,f=(b-x)/(A-x)*G,C=G-f+p,e[k]=document.createElementNS("http://www.w3.org/2000/svg","line"),e[k].setAttribute("x1",J[0]),e[k].setAttribute("y1",C),e[k].setAttribute("x2",h+m),e[k].setAttribute("y2",C),e[k].setAttribute("stroke",
"#FF0000"),e[k].setAttribute("stroke-width",u),e[k].setAttribute("stroke-opacity",E),e[k].setAttribute("visibility","visible"));M[0]=A.toFixed(z);f=(A-x)/4;M[1]=(A-f).toFixed(z);M[2]=(A-2*f).toFixed(z);M[3]=(A-3*f).toFixed(z);M[4]=x.toFixed(z);M[5]="";M[6]="";w<x&&(w=x);w>A&&(w=A);f=G*(1-(w-x)/(A-x));d[0]=document.createElementNS("http://www.w3.org/2000/svg","line");d[0].setAttribute("x1",h+m);d[0].setAttribute("y1",f+p);d[0].setAttribute("x2",h+m+B);d[0].setAttribute("y2",f-B/2+p);d[0].setAttribute("stroke",
v[D]);d[0].setAttribute("stroke-width",2);d[0].setAttribute("stroke-opacity",E);d[0].setAttribute("visibility","visible");d[1]=document.createElementNS("http://www.w3.org/2000/svg","line");d[1].setAttribute("x1",h+m+B);d[1].setAttribute("y1",f-B/2+p);d[1].setAttribute("x2",h+m+B);d[1].setAttribute("y2",f+B/2+p);d[1].setAttribute("stroke",v[D]);d[1].setAttribute("stroke-width",2);d[1].setAttribute("stroke-opacity",E);d[1].setAttribute("visibility","visible");d[2]=document.createElementNS("http://www.w3.org/2000/svg",
"line");d[2].setAttribute("x1",h+m+B);d[2].setAttribute("y1",f+B/2+p);d[2].setAttribute("x2",h+m);d[2].setAttribute("y2",f+p);d[2].setAttribute("stroke",v[D]);d[2].setAttribute("stroke-width",2);d[2].setAttribute("fill","#FF0000");d[2].setAttribute("stroke-opacity",E);d[2].setAttribute("visibility","visible");for(b=0;b<=k;b++)H.appendChild(e[b]);for(b=0;3>b;b++)H.appendChild(d[b]);for(z=b=0;7>z;z++)5==z&&0>C||6==z&&0>c||(n[b]=document.createElementNS("http://www.w3.org/2000/svg","text"),f=5*b,f=5==
z?C+2:6==z?c+2:T[f]+2,0==K?(n[b].setAttribute("text-anchor","start"),n[b].setAttribute("x",m),n[b].setAttribute("y",f)):1==K?(n[b].setAttribute("text-anchor","middle"),n[b].setAttribute("x",m+h/4),n[b].setAttribute("y",f)):2==K&&(n[b].setAttribute("text-anchor","end"),n[b].setAttribute("x",m+h/2-5),n[b].setAttribute("y",f)),1==aa&&n[b].setAttribute("font-style","italic"),n[b].setAttribute("font-size",r),n[b].setAttribute("font-family",q),5==z||6==z?n[b].setAttribute("fill","#FF0000"):n[b].setAttribute("fill",
Q),n[b].setAttribute("font-weight",L),n[b].setAttribute("visibility","visible"),f=document.createTextNode(M[z]),n[b].appendChild(f),H.appendChild(n[b]),b++);ca=b;Q=a.vfcolour;q=parseInt(a.vfnt);r=parseInt(a.vfsiz);K=parseInt(a.vjust);L=parseInt(a.vbold);aa=parseInt(a.vitalic);q=1==q?"Times New Roman":2==q?"Arial":3==q?"Calibri":4==q?"Sans-Serif":5==q?"Verdana":6==q?"Century":"Arial";r=1==r?10:2==r?11:3==r?12:4==r?14:5==r?16:6==r?18:8;L=1==L?"bold":"normal";for(b=0;2>b;b++)g[b]=document.createElementNS("http://www.w3.org/2000/svg",
"text"),0==b?g[b].setAttribute("y",p+G+O+5):g[b].setAttribute("y",p+G+2*O+5),0==K?(g[b].setAttribute("text-anchor","start"),g[b].setAttribute("x",0)):1==K?(g[b].setAttribute("text-anchor","middle"),0!=m?g[b].setAttribute("x",l/2):g[b].setAttribute("x",h/2)):2==K&&(g[b].setAttribute("text-anchor","end"),0!=m?g[b].setAttribute("x",l):g[b].setAttribute("x",h)),1==aa&&g[b].setAttribute("font-style","italic"),g[b].setAttribute("font-size",r),g[b].setAttribute("font-family",q),g[b].setAttribute("fill",
Q),g[b].setAttribute("font-weight",L),g[b].setAttribute("visibility","visible"),f=0==b?document.createTextNode(X+" "+S):document.createTextNode(R),g[b].appendChild(f),H.appendChild(g[b]);ka=1==N?a.name:"";t=document.createElementNS("http://www.w3.org/2000/svg","text");t.setAttribute("x",0);t.setAttribute("y",10);t.setAttribute("font-size",12);t.setAttribute("font-family","Arial");t.setAttribute("font-style","normal");t.setAttribute("fill",a.xarrowcolour);t.setAttribute("font-weight","bold");t.setAttribute("text-anchor",
"left");t.setAttribute("visibility","visible");Q=document.createTextNode(ka);t.appendChild(Q);H.appendChild(t);y=document.createElementNS("http://www.w3.org/2000/svg","rect");y.setAttribute("x",0);y.setAttribute("y",0);y.setAttribute("width",V);y.setAttribute("height",Z);y.setAttribute("fill-opacity",0);y.setAttribute("stroke-opacity",0);y.setAttribute("stroke","#FF0000");y.setAttribute("stroke-width",u);y.setAttribute("fill",0);H.appendChild(y);1==N?a.registercontentsize(da,15):a.registercontentsize(V,
Z);y.addEventListener("click",ja);y.addEventListener("mouseover",ha);y.addEventListener("mouseout",ia);u=getcycletime();u=u.trim();u=parseInt(u);isNaN(u)?u=5:0>=u&&(u=5);setTimeout(la,1E3);ma=setInterval(function(){la()},1E3*u);na=setInterval(function(){pa||1==mack_status()?Y(1):(1==F[D]?2==P||3==P?Y(0):Y(1):2==F[D]&&(1==P||3==P?Y(0):Y(1)),P++,3<P&&(P=0))},500)}function la(a){a=somefunction(ea).split(",");U="";w="i"==I[0]||"I"==I[0]?parseInt(a[0]):"f"==I[0]||"F"==I[0]?parseFloat(a[0]):0;isNaN(w)&&
(w=0);1<a.length?(D=parseInt(a[1]),isNaN(D)&&(D=0),2<a.length&&(U=a[2])):D=0;1!=fa&&(w*=fa);w<x&&(w=x);w>A&&(w=A);B=10;a=G*(1-(w-x)/(A-x));d[0].setAttribute("y1",a+p);d[0].setAttribute("y2",a-B/2+p);d[0].setAttribute("stroke",v[D]);d[1].setAttribute("y1",a-B/2+p);d[1].setAttribute("y2",a+B/2+p);d[1].setAttribute("stroke",v[D]);d[2].setAttribute("y1",a+B/2+p);d[2].setAttribute("y2",a+p);d[2].setAttribute("stroke",v[D]);g[0].setAttribute("fill",v[D]);X=w.toFixed(W)+" "+S+U;g[0].firstChild.nodeValue=
X}function Y(a){1==a?0<D&&1==N&&t.setAttribute("fill-opacity",E):0<D&&1==N&&t.setAttribute("fill-opacity",ba);for(var e=0;3>e;e++)1==a?(d[e].setAttribute("stroke-opacity",E),g[0].setAttribute("fill-opacity",E)):(d[e].setAttribute("stroke-opacity",ba),g[0].setAttribute("fill-opacity",ba))}var ga=null,a=null,H=null,X,g=[],J=[],T=[],B=10,d=[],ma,na,ea,R,S,W,fa,w,A,x,h,G,V,Z,y,e=[],M=[],m,p,da,E,ba,v=[],F=[],D=0,P=0,pa,ka,t,N=1,k,ca,n=[],I=[],U;this.registerplugin=function(c,d,e){ga=c;a=e;a.registerattribute("ver",
"1.0");a.registerattribute("barwidth","40");a.registerattribute("barheight","100");a.registerattribute("scalecolour","0xFFFFFF");a.registerattribute("scalethick","2");a.registerattribute("fcolour","0xFFFF00");a.registerattribute("xarrowcolour","0xFFFF00");a.registerattribute("fnt","5");a.registerattribute("fsiz","0");a.registerattribute("just","0");a.registerattribute("italic","0");a.registerattribute("bold","0");a.registerattribute("scaletag","[default]Tag 2");a.registerattribute("decimalscale",
"0");a.registerattribute("almin","20");a.registerattribute("almax","80");a.registerattribute("maxvalue","100");a.registerattribute("minvalue","0");a.registerattribute("vfcolour","0x0000FF");a.registerattribute("vfnt","5");a.registerattribute("vfsiz","4");a.registerattribute("vjust","1");a.registerattribute("vitalic","0");a.registerattribute("vbold","0");a.registerattribute("units","");a.registerattribute("description","");a.registerattribute("decimals","");a.registerattribute("mult","1.0");a.registerattribute("opacity",
"1.0");a.registerattribute("state0colour","0xFFFF00");a.registerattribute("state1colour","0xFFA500");a.registerattribute("state2colour","0xFF0000");a.registerattribute("state3colour","0x8A2BE2");a.registerattribute("state4colour","0x0000FF");a.registerattribute("state5colour","0xFFFF00");a.registerattribute("state6colour","0xFFA500");a.registerattribute("state7colour","0xFF0000");a.registerattribute("state8colour","0x8A2BE2");a.registerattribute("state9colour","0x0000FF");a.registerattribute("state0blink",
"0");a.registerattribute("state1blink","1");a.registerattribute("state2blink","2");a.registerattribute("state3blink","1");a.registerattribute("state4blink","2");a.registerattribute("state5blink","0");a.registerattribute("state6blink","1");a.registerattribute("state7blink","2");a.registerattribute("state8blink","1");a.registerattribute("state9blink","2");a.handcursor=!1;a.registercontentsize(100,100);H=document.createElementNS("http://www.w3.org/2000/svg","svg");H.style.width="100%";H.style.height=
"100%";a.sprite.appendChild(H);c=Number(a.ver);1==c&&ga.trace(1,"hello from plugin["+a.name+"] version = "+c);oa()};this.unloadplugin=function(){y.removeEventListener("click",ja);y.removeEventListener("mouseover",ha);y.removeEventListener("mouseout",ia);clearInterval(ma);clearInterval(na);ga=a=null}};
