var krpanoplugin=function(){function da(){var d;if(0==I){I=1;for(d=0;d<g;d++)v[d].setAttribute("visibility","hidden"),r[d].setAttribute("visibility","hidden");for(d=0;d<w*g;d++)n[d].setAttribute("visibility","hidden"),e[d].setAttribute("visibility","hidden");q.firstChild.nodeValue="[i]";a.registercontentsize(T,15)}else{for(d=I=0;d<g;d++)v[d].setAttribute("visibility","visible"),r[d].setAttribute("visibility","visible");for(d=0;d<w*g;d++)n[d].setAttribute("visibility","visible"),e[d].setAttribute("visibility",
"visible");q.firstChild.nodeValue="[-]";a.registercontentsize(T,Z)}}function ea(d){a.handcursor=!0}function fa(d){a.handcursor=!1}function na(){var d=[],p,E=[],F=[],m=[],m=[],z,b,c,f,U,G,B,I,J,K,l,x,P;a.colword=a.colword.replace(/0x/gi,"#");a.headercolour=a.headercolour.replace(/0x/gi,"#");a.cellbackgroundcolour=a.cellbackgroundcolour.replace(/0x/gi,"#");a.fcolour=a.fcolour.replace(/0x/gi,"#");a.bordercolour=a.bordercolour.replace(/0x/gi,"#");a.state0colour=a.state0colour.replace(/0x/gi,"#");a.state1colour=
a.state1colour.replace(/0x/gi,"#");a.state2colour=a.state2colour.replace(/0x/gi,"#");a.state3colour=a.state3colour.replace(/0x/gi,"#");a.state4colour=a.state4colour.replace(/0x/gi,"#");a.state5colour=a.state5colour.replace(/0x/gi,"#");a.state6colour=a.state6colour.replace(/0x/gi,"#");a.state7colour=a.state7colour.replace(/0x/gi,"#");a.state8colour=a.state8colour.replace(/0x/gi,"#");a.state9colour=a.state9colour.replace(/0x/gi,"#");t[0]=a.state0colour;t[1]=a.state1colour;t[2]=a.state2colour;t[3]=a.state3colour;
t[4]=a.state4colour;t[5]=a.state5colour;t[6]=a.state6colour;t[7]=a.state7colour;t[8]=a.state8colour;t[9]=a.state9colour;y[0]=parseInt(a.state0blink);y[1]=parseInt(a.state1blink);y[2]=parseInt(a.state2blink);y[3]=parseInt(a.state3blink);y[4]=parseInt(a.state4blink);y[5]=parseInt(a.state5blink);y[6]=parseInt(a.state6blink);y[7]=parseInt(a.state7blink);y[8]=parseInt(a.state8blink);y[9]=parseInt(a.state9blink);P=parseFloat(a.opacity);E.length=0;w=parseInt(a.rows);ga="ARSTATUS";1>w&&(w=1);p=0;E=a.colword.split(":");
1>g&&(g=1);U=parseInt(a.xstart);c=parseInt(a.ystart);B=G=0;5>G&&(G=5);5>B&&(B=5);I=a.bordercolour;J=a.borderthickness;1>J&&(J=1);5<J&&(J=5);f=a.headercolour;V=a.cellbackgroundcolour;K=a.fcolour;l=parseInt(a.fnt);x=parseInt(a.fsiz);z=k.length;W=w*g;z>W&&(z=W,k.length=W);for(b=0;b<z;b++)H[b]="",aa[b]=!1,C[b]=0;for(b=0;b<z;b++)if(m=k[b].split(":"),1<m.length&&(H[b]=m[1],H[b]=H[b].trim()),k[b]=m[0],1<m.length&&(H[b]=m[1]),L[b]=0,0<k[b].length){for(h=0;h<k[b].length;h++)if(" "!=k[b].charAt(h)){L[b]=1;
break}1==L[b]&&"@"==k[b].charAt(h)?(X=L[b]=1,""==H[b]&&(H[b]=" "),m=k[b].split("|"),k[b]=m[0],N[b]=1,O[b]=-1,1<m.length&&(O[b]=parseInt(m[1]),0>O[b]&&(O[b]=-2)),2<m.length&&(N[b]=parseFloat(m[2]),0==N[b]&&(N[b]=1))):(L[b]=0,N[b]=1,O[b]=0)}X=1;if(z<w*g)for(b=z;b<w*g;b++)k[b]=" ",H[b]="",L[b]=0,N[b]=1,O[b]=0,C[b]=0,aa[b]=!1;var h=[],m=[],Y=[],Q=[],R=[];m.length=g;Y.length=g;Q.length=g;R.length=g;h.length=g;d.length=g;for(b=0;b<g;b++)m[b]=0,Y[b]=0,Q[b]=0,R[b]=K,h[b]="",d[b]=0;if(0<E.length)for(b=0;b<
E.length;b++)h=E[b].split(","),0<h.length&&(m[b]=parseInt(h[0]),1<h.length&&(Y[b]=parseInt(h[1])),2<h.length&&(Q[b]=parseInt(h[2])),3<h.length&&(R[b]=h[3]));z=g;E=1==l?"Times New Roman":2==l?"Arial":3==l?"Calibri":4==l?"Sans-Serif":5==l?"Verdana":6==l?"Century":"Arial";x=1==x?10:2==x?11:3==x?12:4==x?14:5==x?16:6==x?18:10;l=K;z="normal";A[0]=U;u[0]=c;for(c=K=0;c<g;c++){F[c]=ba[c].length;for(b=0;b<w;b++){h=k[b*g+c];for(l=0;l<h.length&&" "==h.charAt(l);l++);l<h.length&&"@"==h.charAt(l)&&(l=h.lastIndexOf("/"),
0<l?h=k[b*g+c].substring(l+1):(l=h.lastIndexOf("]"),0<l&&(h=k[b*g+c].substring(l+1))));h.length>F[c]&&(F[c]=h.length)}F[1]+=1;d[c]=Math.round(F[c]*x*.65)+G;A[c+1]=A[c]+d[c]}0==p&&(p=1.2*x+B);for(c=0;c<g;c++)l=R[c],v[c]=document.createElementNS("http://www.w3.org/2000/svg","rect"),v[c].setAttribute("x",A[c]),v[c].setAttribute("y",u[0]),v[c].setAttribute("width",d[c]),v[c].setAttribute("height",p),v[c].setAttribute("stroke-width",J),v[c].setAttribute("stroke",I),v[c].setAttribute("fill",f),v[c].setAttribute("stroke-opacity",
P),v[c].setAttribute("fill-opacity",P),r[c]=document.createElementNS("http://www.w3.org/2000/svg","text"),0==m[c]?(r[c].setAttribute("text-anchor","start"),r[c].setAttribute("x",A[c]+G),r[c].setAttribute("y",u[0]+p/2+B)):1==m[c]?(r[c].setAttribute("text-anchor","middle"),r[c].setAttribute("x",A[c]+d[c]/2),r[c].setAttribute("y",u[0]+p/2+B)):2==m[c]&&(r[c].setAttribute("text-anchor","end"),r[c].setAttribute("x",A[c]+d[c]-G),r[c].setAttribute("y",u[0]+p/2+B)),1==Q[c]&&r[c].setAttribute("font-style",
"italic"),r[c].setAttribute("font-size",x),r[c].setAttribute("font-family",E),r[c].setAttribute("fill",l),r[c].setAttribute("font-weight","bold"),b=document.createTextNode(ba[c]),r[c].appendChild(b),D.appendChild(v[c]),D.appendChild(r[c]);u[0]+=p;for(b=0;b<w;b++)u[b+1]=u[b]+p;for(b=0;b<w;b++){var h;h=b*g;for(c=0;c<g;c++)f=h+c,z=1==Y[c]?"bold":"normal",l=R[c],n[f]=document.createElementNS("http://www.w3.org/2000/svg","rect"),n[f].setAttribute("x",A[c]),n[f].setAttribute("y",u[b]),n[f].setAttribute("width",
d[c]),n[f].setAttribute("height",p),n[f].setAttribute("stroke-width",J),n[f].setAttribute("stroke",I),n[f].setAttribute("fill",V),n[f].setAttribute("stroke-opacity",P),n[f].setAttribute("fill-opacity",P),e[f]=document.createElementNS("http://www.w3.org/2000/svg","text"),0==m[c]?(e[f].setAttribute("text-anchor","start"),e[f].setAttribute("x",A[c]+G),e[f].setAttribute("y",u[b]+p/2+B)):1==m[c]?(e[f].setAttribute("text-anchor","middle"),e[f].setAttribute("x",A[c]+d[c]/2),e[f].setAttribute("y",u[b]+p/
2+B)):2==m[c]&&(e[f].setAttribute("text-anchor","end"),e[f].setAttribute("x",A[c]+d[c]-G),e[f].setAttribute("y",u[b]+p/2+B)),1==Q[c]&&e[f].setAttribute("font-style","italic"),e[f].setAttribute("font-size",x),e[f].setAttribute("font-family",E),e[f].setAttribute("fill",l),e[f].setAttribute("font-weight",z),l=F[f]>=k[f].length?document.createTextNode(k[f]):document.createTextNode(k[f].substring(0,F[f])),0!=L[f]&&(k[f]=k[f].replace("@",""),k[f]=k[f].trim()),e[f].appendChild(l),e[f].setAttribute("visibility",
"visible"),n[f].setAttribute("visibility","visible")}for(b=0;b<g;b++)K+=d[b];T=K+U+U;Z=w*p+u[0];a.registercontentsize(T,Z);for(b=0;b<w*g;b++)D.appendChild(n[b]),D.appendChild(e[b]);ha="[-]";q=document.createElementNS("http://www.w3.org/2000/svg","text");q.setAttribute("x",K-12);q.setAttribute("y",10);q.setAttribute("font-size",10);q.setAttribute("font-family","Arial");q.setAttribute("font-style","normal");q.setAttribute("fill","#ffffff");q.setAttribute("font-weight","bold");q.setAttribute("text-anchor",
"right");q.setAttribute("visibility","visible");d=document.createTextNode(ha);q.appendChild(d);D.appendChild(q);q.addEventListener("click",da);q.addEventListener("mouseover",ea);q.addEventListener("mouseout",fa);1==X&&(S=getcycletime(),S=S.trim(),d=parseInt(S),isNaN(d)?d=5:0>=d&&(d=5),e[1].firstChild.nodeValue=" ",e[3].firstChild.nodeValue=" ",e[5].firstChild.nodeValue=" ",e[7].firstChild.nodeValue=" ",e[9].firstChild.nodeValue=" ",e[11].firstChild.nodeValue=" ",e[13].firstChild.nodeValue=" ",e[15].firstChild.nodeValue=
" ",setTimeout(ia,500),ja=setInterval(function(){ia()},1E3*d),ka=setInterval(function(){aa[15]&&n[15].setAttribute("fill",t[C[15]]);1==y[C[15]]?2==M||3==M?n[15].setAttribute("fill",V):n[15].setAttribute("fill",t[C[15]]):2==y[C[15]]?1==M||3==M?n[15].setAttribute("fill",V):n[15].setAttribute("fill",t[C[15]]):n[15].setAttribute("fill",t[C[15]]);M++;3<M&&(M=0)},500))}function ia(){var a,p;a=somefunction(ga);p=a.split(",");la=getuser();ma=getaccess();e[1].firstChild.nodeValue=la;e[3].firstChild.nodeValue=
ma;e[5].firstChild.nodeValue=p[2];e[7].firstChild.nodeValue=S;e[9].firstChild.nodeValue=p[5];e[11].firstChild.nodeValue=p[3];e[13].firstChild.nodeValue=p[6];a=p[7];C[15]="1"==a?1:0;e[15].firstChild.nodeValue=a;a=p[2];C[5]="1"==a?1:0}var ca=null,a=null,D=null,T,Z,w,g,V,k=[],e=[],n=[],ba=[],r=[],v=[],A=[],u=[],H=[],ja,ka,X,L=[],N=[],O=[],W,t=[],y=[],C=[],M=0,aa=[],S,ga,ha,q,I=0,la,ma;this.registerplugin=function(d,e,n){ca=d;a=n;a.registerattribute("ver","1");a.registerattribute("colvars","Mode;Status;User;Basic;Access;BU;ONLINE;0;CYCLE;5;LICENSE;0;DATE;1;TIME;hh-mm-ss ;PUBNUB;0;");
a.registerattribute("rows","8");a.registerattribute("columns","2");a.registerattribute("colword","0:0");a.registerattribute("xstart","0");a.registerattribute("ystart","0");a.registerattribute("bordercolour","0x000000");a.registerattribute("borderthickness","2");a.registerattribute("headercolour","#0000FF");a.registerattribute("cellbackgroundcolour","#FFFF00");a.registerattribute("fcolour","#000000");a.registerattribute("fnt","5");a.registerattribute("fsiz","1");a.registerattribute("opacity","0.5");
a.registerattribute("state0colour","0xFFFF00");a.registerattribute("state1colour","0xFF0000");a.registerattribute("state2colour","0xFF0000");a.registerattribute("state3colour","0x8A2BE2");a.registerattribute("state4colour","0x0000FF");a.registerattribute("state5colour","0xFFFF00");a.registerattribute("state6colour","0xFFA500");a.registerattribute("state7colour","0xFF0000");a.registerattribute("state8colour","0x8A2BE2");a.registerattribute("state9colour","0x0000FF");a.registerattribute("state0blink",
"0");a.registerattribute("state1blink","1");a.registerattribute("state2blink","2");a.registerattribute("state3blink","1");a.registerattribute("state4blink","2");a.registerattribute("state5blink","0");a.registerattribute("state6blink","1");a.registerattribute("state7blink","2");a.registerattribute("state8blink","1");a.registerattribute("state9blink","2");a.registerattribute("state0","state0");a.registerattribute("state1","state1");a.registerattribute("state2","state2");a.registerattribute("state3",
"state3");a.registerattribute("state4","state4");a.registerattribute("state5","state5");a.registerattribute("state6","state6");a.registerattribute("state7","state7");a.registerattribute("state8","state8");a.registerattribute("state9","state9");a.handcursor=!1;a.registercontentsize(512,512);D=document.createElementNS("http://www.w3.org/2000/svg","svg");D.style.width="100%";D.style.height="100%";a.sprite.appendChild(D);1==Number(a.ver)&&ca.trace(1,"hello from plugin["+a.name+"] version = 1.0");k.length=
0;a.colvars=a.colvars.replace("\n","");a.colvars=a.colvars.replace("\r","");a.colvars=a.colvars.replace("\t","");g=parseInt(a.columns);1>g&&(g=1);k=a.colvars.split(";");d=k.length;""==k[d-1]&&(k.length=d-1);d=[];for(e=0;e<g;e++)d=k[e].split(":"),ba[e]=d[0];for(e=0;e<g;e++)k.shift();d.length=0;na()};this.unloadplugin=function(){q.removeEventListener("click",da);q.removeEventListener("mouseover",ea);q.removeEventListener("mouseout",fa);1==X&&(clearInterval(ja),clearInterval(ka));ca=a=null};this.onresize=
function(a,e){return!1}};
