var krpanoplugin=function(){function B(){0==m?(m=1,0!=t&&d.setAttribute("visibility","hidden"),b.setAttribute("visibility","hidden"),e.firstChild.nodeValue=a.name,a.registercontentsize(w,15)):(m=0,0!=t&&d.setAttribute("visibility","visible"),b.setAttribute("visibility","visible"),e.firstChild.nodeValue="",a.registercontentsize(x,y))}function C(b){a.handcursor=!0}function D(b){a.handcursor=!1}var z=null,a=null,k=null,x,y,q=[],b,f,d,e,E,w,m=0,t;this.registerplugin=function(h,n,l){z=h;a=l;a.registerattribute("ver",
"0");a.registerattribute("cellvar","This is static text");a.registerattribute("fcolour","0x0000ff");a.registerattribute("xarrowcolour","0xffff00");a.registerattribute("fnt","5");a.registerattribute("fsiz","2");a.registerattribute("xpad","0");a.registerattribute("ypad","0");a.registerattribute("fbold","0");a.registerattribute("fitalic","0");a.registerattribute("fjust","1");a.registerattribute("opacity","1.0");a.registerattribute("border","1");a.registerattribute("borderthickness","1");a.registerattribute("bordercolour",
"0x0000FF");a.registerattribute("cellbackgroundcolour","0xffff00");a.handcursor=!1;a.registercontentsize(100,100);k=document.createElementNS("http://www.w3.org/2000/svg","svg");k.style.width="100%";k.style.height="100%";a.sprite.appendChild(k);1==Number(a.ver)&&z.trace(1,"hello from plugin["+a.name+"] version = 1.0");a.cellvar=a.cellvar.replace("\n","");a.cellvar=a.cellvar.replace("\r","");a.cellvar=a.cellvar.replace("\t","");var c,g,p,F,G,u,v,r,H,A,I;q=a.cellvar;n=parseInt(a.xpad);l=parseInt(a.ypad);
0==l&&(l=3);a.cellbackgroundcolour=a.cellbackgroundcolour.replace(/0x/gi,"#");a.fcolour=a.fcolour.replace(/0x/gi,"#");a.xarrowcolour=a.xarrowcolour.replace(/0x/gi,"#");a.bordercolour=a.bordercolour.replace(/0x/gi,"#");G=a.fcolour;g=parseInt(a.fnt);c=parseInt(a.fsiz);u=parseInt(a.fjust);v=parseInt(a.fbold);H=parseInt(a.fitalic);t=parseInt(a.border);A=parseFloat(a.opacity);I=a.cellbackgroundcolour;F=a.bordercolour;h=parseInt(a.borderthickness);p=q.split(":");1<p.length&&p[1].trim();q=p[0];p=1==g?"Times New Roman":
2==g?"Arial":3==g?"Calibri":4==g?"Sans-Serif":5==g?"Verdana":6==g?"Century":"Arial";r=1==c?10:2==c?11:3==c?12:4==c?14:5==c?16:6==c?18:10;c=q.length;1>c&&(c=1);c=Math.round(c*r*.6)+n;w=Math.round(a.name.length*r*.65);g=1.25*r+l;v=1==v?"bold":"normal";d=document.createElementNS("http://www.w3.org/2000/svg","rect");d.setAttribute("x",0+h);d.setAttribute("y",0+h);d.setAttribute("width",c-2*h);d.setAttribute("height",g-2*h);d.setAttribute("fill-opacity",A);d.setAttribute("stroke-opacity",A);d.setAttribute("fill",
I);d.setAttribute("stroke",F);d.setAttribute("stroke-width",h);0==m?d.setAttribute("visibility","visible"):d.setAttribute("visibility","hidden");f=document.createElementNS("http://www.w3.org/2000/svg","rect");f.setAttribute("x",0);f.setAttribute("y",0);f.setAttribute("width",c);f.setAttribute("height",g);f.setAttribute("fill-opacity",0);f.setAttribute("fill",0);b=document.createElementNS("http://www.w3.org/2000/svg","text");0==u?(b.setAttribute("text-anchor","start"),b.setAttribute("x",0+n),b.setAttribute("y",
0+g/2+l)):1==u?(b.setAttribute("text-anchor","middle"),b.setAttribute("x",0+c/2),b.setAttribute("y",0+g/2+l)):2==u&&(b.setAttribute("text-anchor","end"),b.setAttribute("x",0+c-n),b.setAttribute("y",0+g/2+l));1==H&&b.setAttribute("font-style","italic");b.setAttribute("font-size",r);b.setAttribute("font-family",p);b.setAttribute("fill",G);b.setAttribute("font-weight",v);0==m?b.setAttribute("visibility","visible"):b.setAttribute("visibility","hidden");n=document.createTextNode(q);b.appendChild(n);x=
c;y=g;0!=t&&k.appendChild(d);k.appendChild(b);E=0==m?"":a.name;e=document.createElementNS("http://www.w3.org/2000/svg","text");e.setAttribute("x",h);e.setAttribute("y",10);e.setAttribute("font-size",10);e.setAttribute("font-family","Arial");e.setAttribute("font-style","normal");e.setAttribute("fill",a.xarrowcolour);e.setAttribute("font-weight","bold");e.setAttribute("text-anchor","left");e.setAttribute("visibility","visible");h=document.createTextNode(E);e.appendChild(h);k.appendChild(e);k.appendChild(f);
0==m?a.registercontentsize(x,y):a.registercontentsize(w,15);f.addEventListener("click",B);f.addEventListener("mouseover",C);f.addEventListener("mouseout",D)};this.unloadplugin=function(){f.removeEventListener("click",B);f.removeEventListener("mouseover",C);f.removeEventListener("mouseout",D);z=a=null};this.onresize=function(a,b){return!1}};
