var krpanoplugin=function(){function da(){var d;if(0==E){E=1;1==ka&&r.setAttribute("visibility","hidden");z.setAttribute("visibility","hidden");for(d=0;d<n;d++)g[d].setAttribute("visibility","hidden"),v[d].setAttribute("visibility","hidden");for(d=0;d<=la;d++)q[d].setAttribute("visibility","hidden"),m[d].setAttribute("visibility","hidden");k.firstChild.nodeValue=a.name;a.registercontentsize(ma,20)}else{E=0;1==ka&&r.setAttribute("visibility","visible");z.setAttribute("visibility","visible");for(d=
0;d<n;d++)g[d].setAttribute("visibility","visible"),v[d].setAttribute("visibility","visible");for(d=0;d<=la;d++)q[d].setAttribute("visibility","visible"),m[d].setAttribute("visibility","visible");k.firstChild.nodeValue="";a.registercontentsize(ba,V)}}function ea(d){a.handcursor=!0}function fa(d){a.handcursor=!1}function za(){var d=[],e,R=[],ca=[],w=[],p=[],p=[],h,b,c,f,W,P,J,B,Q,S,M,na,x,K,C,oa,ga;a.colword=a.colword.replace(/0x/gi,"#");a.headercolour=a.headercolour.replace(/0x/gi,"#");a.cellbackgroundcolour=
a.cellbackgroundcolour.replace(/0x/gi,"#");a.fcolour=a.fcolour.replace(/0x/gi,"#");a.xarrowcolour=a.xarrowcolour.replace(/0x/gi,"#");a.bordercolour=a.bordercolour.replace(/0x/gi,"#");a.pluginbordercolour=a.pluginbordercolour.replace(/0x/gi,"#");a.pluginfillcolour=a.pluginfillcolour.replace(/0x/gi,"#");a.state0colour=a.state0colour.replace(/0x/gi,"#");a.state1colour=a.state1colour.replace(/0x/gi,"#");a.state2colour=a.state2colour.replace(/0x/gi,"#");a.state3colour=a.state3colour.replace(/0x/gi,"#");
a.state4colour=a.state4colour.replace(/0x/gi,"#");a.state5colour=a.state5colour.replace(/0x/gi,"#");a.state6colour=a.state6colour.replace(/0x/gi,"#");a.state7colour=a.state7colour.replace(/0x/gi,"#");a.state8colour=a.state8colour.replace(/0x/gi,"#");a.state9colour=a.state9colour.replace(/0x/gi,"#");A[0]=a.state0colour;A[1]=a.state1colour;A[2]=a.state2colour;A[3]=a.state3colour;A[4]=a.state4colour;A[5]=a.state5colour;A[6]=a.state6colour;A[7]=a.state7colour;A[8]=a.state8colour;A[9]=a.state9colour;F[0]=
parseInt(a.state0blink);F[1]=parseInt(a.state1blink);F[2]=parseInt(a.state2blink);F[3]=parseInt(a.state3blink);F[4]=parseInt(a.state4blink);F[5]=parseInt(a.state5blink);F[6]=parseInt(a.state6blink);F[7]=parseInt(a.state7blink);F[8]=parseInt(a.state8blink);F[9]=parseInt(a.state9blink);T=parseFloat(a.opacity);ua=.5*T;e=0;R=a.colword.split(":");1>n&&(n=1);W=parseInt(a.xstart);P=parseInt(a.ystart);B=J=0;5>J&&(J=5);5>B&&(B=5);Q=a.bordercolour;S=a.borderthickness;1>S&&(S=1);5<S&&(S=5);M=a.headercolour;
ha=a.cellbackgroundcolour;na=a.fcolour;x=parseInt(a.fnt);K=parseInt(a.fsiz);oa=a.pluginbordercolour;C=a.pluginfillcolour;Y=a.ttitle;h=l.length;Z=G*n;h>Z&&(h=Z,l.length=Z);for(b=0;b<h;b++)U[b]="",pa[b]=!1,t[b]=0;for(b=0;b<h;b++)if(p=l[b].split(":"),1<p.length&&(U[b]=p[1],U[b]=U[b].trim()),l[b]=p[0],1<p.length&&(U[b]=p[1]),N[b]=0,0<l[b].length){for(D=0;D<l[b].length;D++)if(" "!=l[b].charAt(D)){N[b]=1;break}1==N[b]&&"@"==l[b].charAt(D)?(qa=N[b]=1,""==U[b]&&(U[b]=" "),p=l[b].split("|"),l[b]=p[0],L[b]=
1,X[b]=parseInt(aa[4]),1<p.length&&(X[b]=parseInt(p[1]),0>X[b]&&(X[b]=-2)),2<p.length&&(L[b]=parseFloat(p[2]),0==L[b]&&(L[b]=1))):(N[b]=0,L[b]=1,X[b]=0)}if(h<G*n)for(b=h;b<G*n;b++)l[b]=" ",U[b]="",N[b]=0,L[b]=1,X[b]=0,t[b]=0,pa[b]=!1;h=[];var p=[],ra=[],ia=[],ja=[];d.length=n;for(b=0;b<n;b++)p[b]=0,ra[b]=0,ia[b]=0,ja[b]=0;if(0<R.length)for(b=0;b<R.length;b++)h=R[b].split(","),0<h.length&&(p[b]=parseInt(h[0]),1<h.length&&(ra[b]=parseInt(h[1])),2<h.length&&(ia[b]=parseInt(h[2])),3<h.length&&(ja[b]=
h[3]));h=G*n;R=1==x?"Times New Roman":2==x?"Arial":3==x?"Calibri":4==x?"Sans-Serif":5==x?"Verdana":6==x?"Century":"Arial";x=1==K?10:2==K?11:3==K?12:4==K?14:5==K?16:6==K?18:10;ga=na;h="normal";H[0]=W;y[0]=P;for(c=K=0;c<n;c++){ca[c]=sa[c].length;for(b=0;b<G;b++){h=l[b*n+c];for(D=0;D<h.length&&" "==h.charAt(D);D++);D<h.length&&"@"==h.charAt(D)&&(ca[c]=parseInt(aa[3])+10);h.length>ca[c]&&(ca[c]=h.length+2)}d[c]=Math.round(ca[c]*x*.65)+J;H[c+1]=H[c]+d[c]}0==e&&(e=1.2*x+B);ma=Math.round(a.name.length*x*
.65);for(c=0;c<n;c++)ga=ja[c],v[c]=document.createElementNS("http://www.w3.org/2000/svg","rect"),v[c].setAttribute("x",H[c]),v[c].setAttribute("y",y[0]),v[c].setAttribute("width",d[c]),v[c].setAttribute("height",e),v[c].setAttribute("stroke-width",S),v[c].setAttribute("stroke",Q),v[c].setAttribute("fill",M),v[c].setAttribute("stroke-opacity",T),v[c].setAttribute("fill-opacity",T),0==E?v[c].setAttribute("visibility","visible"):v[c].setAttribute("visibility","hidden"),g[c]=document.createElementNS("http://www.w3.org/2000/svg",
"text"),0==p[c]?(g[c].setAttribute("text-anchor","start"),g[c].setAttribute("x",H[c]+J),g[c].setAttribute("y",y[0]+e/2+B)):1==p[c]?(g[c].setAttribute("text-anchor","middle"),g[c].setAttribute("x",H[c]+d[c]/2),g[c].setAttribute("y",y[0]+e/2+B)):2==p[c]&&(g[c].setAttribute("text-anchor","end"),g[c].setAttribute("x",H[c]+d[c]-J),g[c].setAttribute("y",y[0]+e/2+B)),1==ia[c]&&g[c].setAttribute("font-style","italic"),g[c].setAttribute("font-size",x),g[c].setAttribute("font-family",R),g[c].setAttribute("fill",
0),g[c].setAttribute("font-weight","bold"),0==E?g[c].setAttribute("visibility","visible"):g[c].setAttribute("visibility","hidden"),b=document.createTextNode(sa[c]),g[c].appendChild(b);y[0]+=e;for(b=0;b<G;b++)y[b+1]=y[b]+e;for(b=0;b<G;b++){var D;D=b*n;for(c=0;c<n;c++)f=D+c,h=1==ra[c]?"bold":"normal",ga=ja[c],q[f]=document.createElementNS("http://www.w3.org/2000/svg","rect"),q[f].setAttribute("x",H[c]),q[f].setAttribute("y",y[b]),q[f].setAttribute("width",d[c]),q[f].setAttribute("height",e),q[f].setAttribute("stroke-width",
S),q[f].setAttribute("stroke",Q),q[f].setAttribute("fill",ha),q[f].setAttribute("stroke-opacity",T),q[f].setAttribute("fill-opacity",T),0==E?q[f].setAttribute("visibility","visible"):q[f].setAttribute("visibility","hidden"),m[f]=document.createElementNS("http://www.w3.org/2000/svg","text"),0==p[c]?(m[f].setAttribute("text-anchor","start"),m[f].setAttribute("x",H[c]+J),m[f].setAttribute("y",y[b]+e/2+B)):1==p[c]?(m[f].setAttribute("text-anchor","middle"),m[f].setAttribute("x",H[c]+d[c]/2),m[f].setAttribute("y",
y[b]+e/2+B)):2==p[c]&&(m[f].setAttribute("text-anchor","end"),m[f].setAttribute("x",H[c]+d[c]-J),m[f].setAttribute("y",y[b]+e/2+B)),1==ia[c]&&m[f].setAttribute("font-style","italic"),m[f].setAttribute("font-size",x),m[f].setAttribute("font-family",R),m[f].setAttribute("fill",ga),m[f].setAttribute("font-weight",h),0==E?m[f].setAttribute("visibility","visible"):m[f].setAttribute("visibility","hidden"),M=1==N[f]?document.createTextNode(" "):document.createTextNode(l[f]),0!=N[f]&&(l[f]=l[f].replace("@",
""),l[f]=l[f].trim()),m[f].appendChild(M)}la=f;for(b=0;b<n;b++)K+=d[b];ba=K+W+W;V=G*e+y[0];0<Y.length&&(V=V+e+2*S);z=document.createElementNS("http://www.w3.org/2000/svg","rect");z.setAttribute("x",0);z.setAttribute("y",0);z.setAttribute("width",ba);z.setAttribute("height",V);z.setAttribute("stroke",oa);z.setAttribute("fill",C);z.setAttribute("fill-opacity",T);z.setAttribute("stroke-width",1);0==E?z.setAttribute("visibility","visible"):z.setAttribute("visibility","hidden");I.appendChild(z);for(b=
0;b<G*n;b++)I.appendChild(q[b]),I.appendChild(m[b]);for(c=0;c<n;c++)I.appendChild(v[c]),I.appendChild(g[c]);0<Y.length&&(0==Y.length&&(Y=" "),ka=1,w.length=0,w=Y.split(":"),f=e=d=0,1<w.length&&(2==w.length?d=parseInt(w[1]):3==w.length?(d=parseInt(w[1]),e=parseInt(w[2])):4==w.length&&(d=parseInt(w[1]),e=parseInt(w[2]),f=parseInt(w[3]))),h="normal",B="none",J="normal",0!=d&&(h="bold"),0!=e&&(B="underline"),0!=f&&(J="italic"),r=document.createElementNS("http://www.w3.org/2000/svg","text"),r.setAttribute("x",
H[0]+K/2),r.setAttribute("y",y[G]+x),r.setAttribute("font-size",x),r.setAttribute("font-family",R),r.setAttribute("text-decoration",B),r.setAttribute("font-style",J),r.setAttribute("fill",na),r.setAttribute("font-weight",h),r.setAttribute("text-anchor","middle"),0==E?r.setAttribute("visibility","visible"):r.setAttribute("visibility","hidden"),w=document.createTextNode(w[0]),r.appendChild(w),I.appendChild(r));va=0==E?"":a.name;k=document.createElementNS("http://www.w3.org/2000/svg","text");k.setAttribute("x",
W);k.setAttribute("y",P+10);k.setAttribute("font-size",12);k.setAttribute("font-family","Arial");k.setAttribute("font-style","normal");k.setAttribute("fill",a.xarrowcolour);k.setAttribute("font-weight","bold");k.setAttribute("text-anchor","left");k.setAttribute("visibility","visible");W=document.createTextNode(va);k.appendChild(W);k.addEventListener("click",da);k.addEventListener("mouseover",ea);k.addEventListener("mouseout",fa);I.appendChild(k);u=document.createElementNS("http://www.w3.org/2000/svg",
"rect");u.setAttribute("x",0);u.setAttribute("y",0);u.setAttribute("width",ba);u.setAttribute("height",V);u.setAttribute("stroke",oa);u.setAttribute("fill",C);u.setAttribute("fill-opacity",0);u.setAttribute("stroke-width",1);I.appendChild(u);u.addEventListener("click",da);u.addEventListener("mouseover",ea);u.addEventListener("mouseout",fa);0==E?a.registercontentsize(ba,V):a.registercontentsize(ma,20);1==qa&&(C=getcycletime(),C=C.trim(),C=parseInt(C),isNaN(C)?C=5:0>=C&&(C=5),setTimeout(wa,1E3),xa=
setInterval(function(){wa()},1E3*C),ya=setInterval(function(){var a,b;b=mack_status();1==E&&(0<ta&&(0==O||2==O)?k.setAttribute("fill-opacity",ua):k.setAttribute("fill-opacity",T));for(a=0;a<Z;a++)pa[a]||b?q[a].setAttribute("fill",A[t[a]]):1==F[t[a]]?2==O||3==O?q[a].setAttribute("fill",ha):q[a].setAttribute("fill",A[t[a]]):2==F[t[a]]?1==O||3==O?q[a].setAttribute("fill",ha):q[a].setAttribute("fill",A[t[a]]):q[a].setAttribute("fill",A[t[a]]);O++;3<O&&(O=0)},500))}function wa(){var a,e,k,g;for(e=ta=0;e<
Z;e++)1==N[e]?(a=somefunction(l[e]),g=a.split(","),P="",a=g[0],k=Math.floor(e/n),t[e]=1<g.length?parseInt(g[1]):0,0<t[e]&&(ta=1),9<t[e]&&(Q.trace(1,"state > 9:"+t[e]),t[e]=9),0>t[e]&&(Q.trace(1,"state < 0:"+t[e]),t[e]=0),2<g.length&&(P=g[2]),"i"==M[k]||"I"==M[k]?(a=parseInt(a),isNaN(a)&&(a=0),1!=L[e]&&(a*=L[e]),m[e].firstChild.nodeValue=a+P):"f"==M[k]||"F"==M[k]?(a=parseFloat(a),isNaN(a)&&(a=0),1!=L[e]&&(a*=L[e]),m[e].firstChild.nodeValue=a.toFixed(X[e])+P):m[e].firstChild.nodeValue=a+" "+P):m[e].firstChild.nodeValue=
l[e]}var Q=null,a=null,I=null,ba,V,G,n,z,Y,r,ha,l=[],m=[],q=[],u,sa=[],g=[],v=[],H=[],y=[],U=[],xa,ya,qa,N=[],L=[],X=[],M=[],Z,A=[],F=[],t=[],O=0,pa=[],k,va,ma,E=1,la,ka=0,aa=[],P,ta=0,T,ua;this.registerplugin=function(d,e,g){Q=d;a=g;a.registerattribute("ver","0");a.registerattribute("tabletags","[default]Tag 0;[default]Tag 102;[default]Tag 2;[default]Tag 3;[default]Tag 0;[default]Tag 102;[default]Tag 2;[default]Tag 3");a.registerattribute("ttitle","Room tarrif per night:1:1:1");a.registerattribute("rows",
"4");a.registerattribute("columns","5");a.registerattribute("colword","1,1,0,#000000:0:2,1,1,#000000:0:0");a.registerattribute("xstart","10");a.registerattribute("ystart","10");a.registerattribute("bordercolour","0x000000");a.registerattribute("borderthickness","2");a.registerattribute("headercolour","#0000FF");a.registerattribute("cellbackgroundcolour","#FFFF00");a.registerattribute("fcolour","#FF0000");a.registerattribute("xarrowcolour","#FFFF00");a.registerattribute("fnt","5");a.registerattribute("fsiz",
"2");a.registerattribute("opacity","1.0");a.registerattribute("pluginbordercolour","#000000");a.registerattribute("pluginfillcolour","#0000FF");a.registerattribute("state0colour","0xFFFF00");a.registerattribute("state1colour","0xFFA500");a.registerattribute("state2colour","0xFF0000");a.registerattribute("state3colour","0x8A2BE2");a.registerattribute("state4colour","0x0000FF");a.registerattribute("state5colour","0xFFFF00");a.registerattribute("state6colour","0xFFA500");a.registerattribute("state7colour",
"0xFF0000");a.registerattribute("state8colour","0x8A2BE2");a.registerattribute("state9colour","0x0000FF");a.registerattribute("state0blink","0");a.registerattribute("state1blink","1");a.registerattribute("state2blink","2");a.registerattribute("state3blink","1");a.registerattribute("state4blink","2");a.registerattribute("state5blink","0");a.registerattribute("state6blink","1");a.registerattribute("state7blink","2");a.registerattribute("state8blink","1");a.registerattribute("state9blink","2");a.registerattribute("state0",
"state0");a.registerattribute("state1","state1");a.registerattribute("state2","state2");a.registerattribute("state3","state3");a.registerattribute("state4","state4");a.registerattribute("state5","state5");a.registerattribute("state6","state6");a.registerattribute("state7","state7");a.registerattribute("state8","state8");a.registerattribute("state9","state9");a.handcursor=!1;a.registercontentsize(512,512);I=document.createElementNS("http://www.w3.org/2000/svg","svg");I.style.width="100%";I.style.height=
"100%";a.sprite.appendChild(I);1==Number(a.ver)&&Q.trace(1,"hello from plugin["+a.name+"] version = 1.0");l.length=0;n=5;1>n&&(n=1);e=a.tabletags.split(";");20<e.length&&(e.length=20);g="SrNo;Tag;Drscription;Units;Status";G=e.length;for(d=0;d<G;d++)aa=getattr(e[d]).split(","),g+=";"+(d+1)+";"+e[d]+";"+aa[1]+";"+aa[2]+";@"+e[d],M[d]=aa[0];l=g.split(";");d=l.length;""==l[d-1]&&(l.length=d-1);e=[];for(d=0;d<n;d++)e=l[d].split(":"),sa[d]=e[0];for(d=0;d<n;d++)l.shift();e.length=0;za()};this.unloadplugin=
function(){u.removeEventListener("click",da);u.removeEventListener("mouseover",ea);u.removeEventListener("mouseout",fa);k.removeEventListener("click",da);k.removeEventListener("mouseover",ea);k.removeEventListener("mouseout",fa);1==qa&&(clearInterval(xa),clearInterval(ya));Q=a=null};this.onresize=function(a,e){return!1}};
