var krpanoplugin=function(){function aa(e){a.handcursor=!0}function ba(e){a.handcursor=!1}function ua(){if(0!=G)X(),G=0;else{for(var e=0;e<z;e++)for(var d=e*v*h,g=0;g<v;g++)for(var l=g*h,n=0;n<h;n++){var m=d+l+n;q[m].setAttribute("visibility","hidden");k[m].setAttribute("visibility","hidden")}1<z&&(r.setAttribute("visibility","hidden"),p.setAttribute("visibility","hidden"));I.setAttribute("visibility","hidden");null!=A&&A.setAttribute("visibility","hidden");for(g=0;g<h;g++)F[g].setAttribute("visibility",
"hidden"),t[g].setAttribute("visibility","hidden");y.setAttribute("fill-opacity",S);y.firstChild.nodeValue=a.name;a.registercontentsize(pa,15);G=1}}function va(a){x--;0==x?r.setAttribute("visibility","hidden"):(ca=String("<"+x),r.firstChild.nodeValue=ca);p.setAttribute("visibility","visible");da=String(x+2+">");p.firstChild.nodeValue=da;X()}function wa(a){x++;x==z-1?p.setAttribute("visibility","hidden"):(da=String(x+2+">"),p.firstChild.nodeValue=da);r.setAttribute("visibility","visible");ca="<"+x;
r.firstChild.nodeValue=ca;X()}function X(){for(var e=0;e<z;e++)for(var d=e*v*h,g=0;g<v;g++)for(var l=g*h,n=0;n<h;n++){var m=d+l+n;e!=x?(k[m].setAttribute("visibility","hidden"),q[m].setAttribute("visibility","hidden")):(q[m].setAttribute("visibility","visible"),k[m].setAttribute("visibility","visible"))}0<x&&r.setAttribute("visibility","visible");x<z-1&&p.setAttribute("visibility","visible");I.setAttribute("visibility","visible");null!=A&&A.setAttribute("visibility","visible");for(g=0;g<h;g++)F[g].setAttribute("visibility",
"visible"),t[g].setAttribute("visibility","visible");y.setAttribute("fill-opacity",S);y.firstChild.nodeValue="";a.registercontentsize(ia,ea)}function Da(){var e=[],d,g=[],H=[],n=[],m=[],m=[],c,b,f,x,fa,N,M,ga,Q,P,w,D,V,W,la;a.colword=a.colword.replace(/0x/gi,"#");a.headercolour=a.headercolour.replace(/0x/gi,"#");a.cellbackgroundcolour=a.cellbackgroundcolour.replace(/0x/gi,"#");a.fcolour=a.fcolour.replace(/0x/gi,"#");a.xarrowcolour=a.xarrowcolour.replace(/0x/gi,"#");a.bordercolour=a.bordercolour.replace(/0x/gi,
"#");a.pluginbordercolour=a.pluginbordercolour.replace(/0x/gi,"#");a.pluginfillcolour=a.pluginfillcolour.replace(/0x/gi,"#");a.state0colour=a.state0colour.replace(/0x/gi,"#");a.state1colour=a.state1colour.replace(/0x/gi,"#");a.state2colour=a.state2colour.replace(/0x/gi,"#");a.state3colour=a.state3colour.replace(/0x/gi,"#");a.state4colour=a.state4colour.replace(/0x/gi,"#");a.state5colour=a.state5colour.replace(/0x/gi,"#");a.state6colour=a.state6colour.replace(/0x/gi,"#");a.state7colour=a.state7colour.replace(/0x/gi,
"#");a.state8colour=a.state8colour.replace(/0x/gi,"#");a.state9colour=a.state9colour.replace(/0x/gi,"#");J[0]=a.state0colour;J[1]=a.state1colour;J[2]=a.state2colour;J[3]=a.state3colour;J[4]=a.state4colour;J[5]=a.state5colour;J[6]=a.state6colour;J[7]=a.state7colour;J[8]=a.state8colour;J[9]=a.state9colour;O[0]=parseInt(a.state0blink);O[1]=parseInt(a.state1blink);O[2]=parseInt(a.state2blink);O[3]=parseInt(a.state3blink);O[4]=parseInt(a.state4blink);O[5]=parseInt(a.state5blink);O[6]=parseInt(a.state6blink);
O[7]=parseInt(a.state7blink);O[8]=parseInt(a.state8blink);O[9]=parseInt(a.state9blink);S=parseFloat(a.opacity);xa=.5*S;d=0;v=parseInt(a.rows);1>v&&(v=1);d=0;g=a.colword.split(":");x=parseInt(a.xstart);fa=parseInt(a.ystart);M=N=0;5>N&&(N=5);5>M&&(M=5);ga=a.bordercolour;Q=parseInt(a.borderthickness);1>Q&&(Q=1);5<Q&&(Q=5);f=a.headercolour;ma=a.cellbackgroundcolour;P=a.fcolour;w=parseInt(a.fnt);D=parseInt(a.fsiz);W=a.pluginbordercolour;V=a.pluginfillcolour;ha=a.ttitle;c=l.length;z=Math.ceil(c/h/v);qa=
z*v*h;for(b=0;b<c;b++)Y[b]="",ra[b]=!1,E[b]=0;for(b=0;b<c;b++)if(m=l[b].split(":"),1<m.length&&(Y[b]=m[1],Y[b]=Y[b].trim()),l[b]=m[0],0<l[b].length){for(u=T[b]=0;u<l[b].length;u++)if(" "!=l[b].charAt(u)){T[b]=1;break}1==T[b]&&"@"==l[b].charAt(u)?(sa=T[b]=1,""==Y[b]&&(Y[b]=" "),m=l[b].split("|"),l[b]=m[0],R[b]=1,Z[b]=parseInt(ja[4]),1<m.length&&(Z[b]=parseInt(m[1]),0>Z[b]&&(Z[b]=-2)),2<m.length&&(R[b]=parseFloat(m[2]),0==R[b]&&(R[b]=1))):(T[b]=0,R[b]=1,Z[b]=0)}if(c<z*v*h)for(b=c;b<z*v*h;b++)l[b]=" ",
Y[b]="",T[b]=0,R[b]=1,Z[b]=0,E[b]=0,ra[b]=!1;var u=[],m=[],X=[],na=[],oa=[];for(b=0;b<h;b++)m[b]=0,X[b]=0,na[b]=0,oa[b]=0,e[b]=0;if(0<g.length)for(b=0;b<g.length;b++)u=g[b].split(","),0<u.length&&(m[b]=parseInt(u[0]),1<u.length&&(X[b]=parseInt(u[1])),2<u.length&&(na[b]=parseInt(u[2])),3<u.length&&(oa[b]=u[3]));c=v*h*z;g=1==w?"Times New Roman":2==w?"Arial":3==w?"Calibri":4==w?"Sans-Serif":5==w?"Verdana":6==w?"Century":"Arial";D=1==D?10:2==D?11:3==D?12:4==D?14:5==D?16:6==D?18:10;la=P;w="normal";K[0]=
x;B[0]=fa;for(c=fa=0;c<h;c++){H[c]=ta[c].length;for(b=0;b<v*z;b++){w=l[b*h+c];for(u=0;u<w.length&&" "==w.charAt(u);u++);u<w.length&&w.charAt(u);w.length>H[c]&&(H[c]=w.length+2)}e[c]=Math.round(H[c]*D*.65)+N;K[c+1]=K[c]+e[c]}0==d&&(d=1.2*D+M);pa=Math.round(a.name.length*D*.65);for(c=0;c<h;c++)la=oa[c],F[c]=document.createElementNS("http://www.w3.org/2000/svg","rect"),F[c].setAttribute("x",K[c]),F[c].setAttribute("y",B[0]),F[c].setAttribute("width",e[c]),F[c].setAttribute("height",d),F[c].setAttribute("stroke-width",
Q),F[c].setAttribute("stroke",ga),F[c].setAttribute("fill",f),F[c].setAttribute("stroke-opacity",S),F[c].setAttribute("fill-opacity",S),0==G?F[c].setAttribute("visibility","visible"):F[c].setAttribute("visibility","hidden"),t[c]=document.createElementNS("http://www.w3.org/2000/svg","text"),0==m[c]?(t[c].setAttribute("text-anchor","start"),t[c].setAttribute("x",K[c]+N),t[c].setAttribute("y",B[0]+d/2+M)):1==m[c]?(t[c].setAttribute("text-anchor","middle"),t[c].setAttribute("x",K[c]+e[c]/2),t[c].setAttribute("y",
B[0]+d/2+M)):2==m[c]&&(t[c].setAttribute("text-anchor","end"),t[c].setAttribute("x",K[c]+e[c]-N),t[c].setAttribute("y",B[0]+d/2+M)),1==na[c]&&t[c].setAttribute("font-style","italic"),t[c].setAttribute("font-size",D),t[c].setAttribute("font-family",g),t[c].setAttribute("fill",0),t[c].setAttribute("font-weight","bold"),t[c].setAttribute("width",e[c]),t[c].setAttribute("height",d),0==G?t[c].setAttribute("visibility","visible"):t[c].setAttribute("visibility","hidden"),b=document.createTextNode(ta[c]),
t[c].appendChild(b),L.appendChild(F[c]),L.appendChild(t[c]);B[0]+=d;for(H=0;H<z;H++)for(b=0;b<v;b++)B[H*v+b+1]=B[b]+d;for(H=0;H<z;H++){var ya;ya=H*v*h;for(b=0;b<v;b++){var u;u=b*h;for(c=0;c<h;c++)f=ya+u+c,w=1==X[c]?"bold":"normal",la=oa[c],q[f]=document.createElementNS("http://www.w3.org/2000/svg","rect"),q[f].setAttribute("x",K[c]),q[f].setAttribute("y",B[b]),q[f].setAttribute("width",e[c]),q[f].setAttribute("height",d),q[f].setAttribute("stroke-width",Q),q[f].setAttribute("stroke",ga),q[f].setAttribute("fill",
ma),q[f].setAttribute("stroke-opacity",S),q[f].setAttribute("fill-opacity",S),q[f].setAttribute("visibility","visible"),k[f]=document.createElementNS("http://www.w3.org/2000/svg","text"),0==m[c]?(k[f].setAttribute("text-anchor","start"),k[f].setAttribute("x",K[c]+N),k[f].setAttribute("y",B[b]+d/2+M)):1==m[c]?(k[f].setAttribute("text-anchor","middle"),k[f].setAttribute("x",K[c]+e[c]/2),k[f].setAttribute("y",B[b]+d/2+M)):2==m[c]&&(k[f].setAttribute("text-anchor","end"),k[f].setAttribute("x",K[c]+e[c]-
N),k[f].setAttribute("y",B[b]+d/2+M)),1==na[c]&&k[f].setAttribute("font-style","italic"),k[f].setAttribute("font-size",D),k[f].setAttribute("font-family",g),k[f].setAttribute("fill",la),k[f].setAttribute("font-weight",w),0==G?k[f].setAttribute("visibility","visible"):k[f].setAttribute("visibility","hidden"),w=1==T[f]?document.createTextNode(" "):document.createTextNode(l[f]),0!=T[f]&&(l[f]=l[f].replace("@",""),l[f]=l[f].trim()),k[f].appendChild(w),0!=H||1==G?k[f].setAttribute("visibility","hidden"):
k[f].setAttribute("visibility","visible"),0!=H||1==G?q[f].setAttribute("visibility","hidden"):q[f].setAttribute("visibility","visible")}}for(b=0;b<h;b++)fa+=e[b];ia=fa+x+x;ea=v*d+B[0];if(0<ha.length||1<z)ea+=d;I=document.createElementNS("http://www.w3.org/2000/svg","rect");I.setAttribute("x",0);I.setAttribute("y",0);I.setAttribute("width",ia);I.setAttribute("height",ea);I.setAttribute("stroke",W);I.setAttribute("fill",V);I.setAttribute("fill-opacity",.25);I.setAttribute("stroke-width",1);0==G?I.setAttribute("visibility",
"visible"):I.setAttribute("visibility","hidden");L.appendChild(I);for(b=0;b<z*v*h;b++)L.appendChild(q[b]),L.appendChild(k[b]);if(0<ha.length||1<z)0==ha.length&&(ha=" "),n.length=0,n=ha.split(":"),M=N=x=0,1<n.length&&(2==n.length?x=parseInt(n[1]):3==n.length?(x=parseInt(n[1]),N=parseInt(n[2])):4==n.length&&(x=parseInt(n[1]),N=parseInt(n[2]),M=parseInt(n[3]))),w="normal",Q="none",ga="normal",0!=x&&(w="bold"),0!=N&&(Q="underline"),0!=M&&(ga="italic"),A=document.createElementNS("http://www.w3.org/2000/svg",
"text"),A.setAttribute("x",K[0]+fa/2),A.setAttribute("y",B[v]+.7*d),A.setAttribute("font-size",D),A.setAttribute("font-family",g),A.setAttribute("text-decoration",Q),A.setAttribute("font-style",ga),A.setAttribute("fill",P),A.setAttribute("font-weight",w),A.setAttribute("text-anchor","middle"),0==G?A.setAttribute("visibility","visible"):A.setAttribute("visibility","hidden"),n=document.createTextNode(n[0]),A.appendChild(n),L.appendChild(A),1<z&&(ca="<0",r=document.createElementNS("http://www.w3.org/2000/svg",
"text"),r.setAttribute("x",K[0]+5),r.setAttribute("y",B[v]+.8*d),r.setAttribute("font-size",D),r.setAttribute("font-family",g),r.setAttribute("font-style","normal"),r.setAttribute("fill",P),r.setAttribute("text-anchor","left"),r.setAttribute("visibility","hidden"),r.addEventListener("click",va),r.addEventListener("mouseover",aa),r.addEventListener("mouseout",ba),n=document.createTextNode(ca),r.appendChild(n),L.appendChild(r),da="2>",p=document.createElementNS("http://www.w3.org/2000/svg","text"),
p.setAttribute("x",K[h-1]+e[h-1]-5),p.setAttribute("y",B[v]+.8*d),p.setAttribute("font-size",D),p.setAttribute("font-family",g),p.setAttribute("font-style","normal"),p.setAttribute("fill",P),p.setAttribute("text-anchor","end"),0==G?p.setAttribute("visibility","visible"):p.setAttribute("visibility","hidden"),p.addEventListener("click",wa),p.addEventListener("mouseover",aa),p.addEventListener("mouseout",ba),e=document.createTextNode(da),p.appendChild(e),L.appendChild(p));za=0==G?"":a.name;y=document.createElementNS("http://www.w3.org/2000/svg",
"text");y.setAttribute("x",0);y.setAttribute("y",8);y.setAttribute("font-size",12);y.setAttribute("font-family","Arial");y.setAttribute("font-style","normal");y.setAttribute("fill",a.xarrowcolour);y.setAttribute("font-weight","bold");y.setAttribute("text-anchor","left");y.setAttribute("visibility","visible");y.setAttribute("fill-opacity","opacity");e=document.createTextNode(za);y.appendChild(e);L.appendChild(y);C=document.createElementNS("http://www.w3.org/2000/svg","rect");C.setAttribute("x",0);
C.setAttribute("y",0);C.setAttribute("width",ia);C.setAttribute("height",ea-d-10);C.setAttribute("stroke",W);C.setAttribute("fill",V);C.setAttribute("fill-opacity",0);C.setAttribute("stroke-opacity",0);C.setAttribute("stroke-width",1);L.appendChild(C);C.addEventListener("click",ua);C.addEventListener("mouseover",aa);C.addEventListener("mouseout",ba);0==G?a.registercontentsize(ia,ea):a.registercontentsize(pa,15);1==sa&&(d=getcycletime(),d=d.trim(),d=parseInt(d),isNaN(d)?d=5:0>=d&&(d=5),setTimeout(Aa,
1E3),Ba=setInterval(function(){Aa()},1E3*d),Ca=setInterval(function(){var a,b;1==G&&0<ka&&(0<ka&&(0==U||2==U)?y.setAttribute("fill-opacity",xa):y.setAttribute("fill-opacity",S));b=mack_status();for(a=0;a<qa;a++)ra[a]||b?q[a].setAttribute("fill",J[E[a]]):1==O[E[a]]?2==U||3==U?q[a].setAttribute("fill",ma):q[a].setAttribute("fill",J[E[a]]):2==O[E[a]]?1==U||3==U?q[a].setAttribute("fill",ma):q[a].setAttribute("fill",J[E[a]]):q[a].setAttribute("fill",J[E[a]]);U++;3<U&&(U=0)},500))}function Aa(){var a,d,
g;for(d=ka=0;d<qa;d++)1==T[d]?(a=somefunction(l[d]),g=a.split(","),P="",a=g[0],E[d]=1<g.length?parseInt(g[1]):0,0<E[d]&&(ka=1),9<E[d]&&(V.trace(1,"state > 9:"+E[d]),E[d]=9),0>E[d]&&(V.trace(1,"state < 0:"+E[d]),E[d]=0),2<g.length&&(P=g[2]),j=Math.floor(d/h),"i"==W[j]||"I"==W[j]?(a=parseInt(a),isNaN(a)&&(a=0),1!=R[d]&&(a*=R[d]),k[d].firstChild.nodeValue=a+P):"f"==W[j]||"F"==W[j]?(a=parseFloat(a),isNaN(a)&&(a=0),1!=R[d]&&(a*=R[d]),k[d].firstChild.nodeValue=a.toFixed(Z[d])+P):k[d].firstChild.nodeValue=
a+" "+P):k[d].firstChild.nodeValue=l[d]}var V=null,a=null,L=null,ia,ea,v,h,G=1,x=0,z=1,r,p,y,za,pa,ca,da,I,C,ha,A,ma,l=[],k=[],q=[],ta=[],t=[],F=[],K=[],B=[],Y=[],Ba,Ca,sa,T=[],R=[],Z=[],W=[],qa,J=[],O=[],E=[],U=0,ka=0,ra=[],ja=[],P,ka=0,S,xa;this.registerplugin=function(e,d,g){V=e;a=g;a.registerattribute("ver","0");a.registerattribute("tabletags","[default]Tag 0;[default]Tag 102;[default]Tag 2;[default]Tag 3;[default]Tag 0;[default]Tag 102;[default]Tag 2;[default]Tag 3");a.registerattribute("rows",
"4");a.registerattribute("columns","5");a.registerattribute("colword","1,1,0,0x000000:0:2,1,1,0x000000:0:0");a.registerattribute("xstart","10");a.registerattribute("ystart","10");a.registerattribute("bordercolour","0x000000");a.registerattribute("borderthickness","2");a.registerattribute("headercolour","0x0000FF");a.registerattribute("cellbackgroundcolour","0xFFFF00");a.registerattribute("fcolour","0xFF0000");a.registerattribute("xarrowcolour","0xFFFF00");a.registerattribute("fnt","5");a.registerattribute("fsiz",
"2");a.registerattribute("opacity","1.0");a.registerattribute("pluginbordercolour","0x000000");a.registerattribute("pluginfillcolour","0x0000FF");a.registerattribute("state0colour","0xFFFF00");a.registerattribute("state1colour","0xFFA500");a.registerattribute("state2colour","0xFF0000");a.registerattribute("state3colour","0x8A2BE2");a.registerattribute("state4colour","0x0000FF");a.registerattribute("state5colour","0xFFFF00");a.registerattribute("state6colour","0xFFA500");a.registerattribute("state7colour",
"0xFF0000");a.registerattribute("state8colour","0x8A2BE2");a.registerattribute("state9colour","0x0000FF");a.registerattribute("state0blink","0");a.registerattribute("state1blink","1");a.registerattribute("state2blink","2");a.registerattribute("state3blink","1");a.registerattribute("state4blink","2");a.registerattribute("state5blink","0");a.registerattribute("state6blink","1");a.registerattribute("state7blink","2");a.registerattribute("state8blink","1");a.registerattribute("state9blink","2");a.registerattribute("state0",
"state0");a.registerattribute("state1","state1");a.registerattribute("state2","state2");a.registerattribute("state3","state3");a.registerattribute("state4","state4");a.registerattribute("state5","state5");a.registerattribute("state6","state6");a.registerattribute("state7","state7");a.registerattribute("state8","state8");a.registerattribute("state9","state9");a.handcursor=!1;a.registercontentsize(512,512);L=document.createElementNS("http://www.w3.org/2000/svg","svg");L.style.width="100%";L.style.height=
"100%";a.sprite.appendChild(L);1==Number(a.ver)&&V.trace(1,"hello from plugin["+a.name+"] version = 1.0");l.length=0;h=5;1>h&&(h=1);d=a.tabletags.split(";");g="SrNo;Tag;Drscription;Units;Status";var k=d.length;for(e=0;e<k;e++)ja=getattr(d[e]).split(","),g+=";"+(e+1)+";"+d[e]+";"+ja[1]+";"+ja[2]+";@"+d[e],W[e]=ja[0];l=g.split(";");e=l.length;""==l[e-1]&&(l.length=e-1);d=[];for(e=0;e<h;e++)d=l[e].split(":"),ta[e]=d[0];for(e=0;e<h;e++)l.shift();d.length=0;Da()};this.unloadplugin=function(){C.removeEventListener("click",
ua);C.removeEventListener("mouseover",aa);C.removeEventListener("mouseout",ba);1<z&&(r.removeEventListener("click",va),r.removeEventListener("mouseover",aa),r.removeEventListener("mouseout",ba),p.removeEventListener("click",wa),p.removeEventListener("mouseover",aa),p.removeEventListener("mouseout",ba));1==sa&&(clearInterval(Ba),clearInterval(Ca));V=a=null};this.onresize=function(a,d){return!1}};
