var REMOTE=2,mm,ctime,curtime,histtime,maxtime,blinkloopon=0,ttime,MenuList=[],MENU_MODE="",TAGS="",TAGSFILE,DEFAULT_TAGSFILE,HOSTNAME,PROJECTNAME,PORT,NJPORT="",DEFAULTUSER="admin",LICENSE="0",dwg_loaded=0,file_read=0,dname,EDIT=1,SNO=[],STATE=[],TIMESTAMP=[],TAG=[],STATECHANGE=[],ACK=[],UNIQ=[],no_alarms=0,no_uniq=0,statefilter="",tagfilter="",buffer="",buffer1="",buffer2="",buffer3="",buffer4="",buffer5="",buffer6="",buffer7="",scenename="",cycle_time,buffer_not_recd=0,buffer1_not_recd=0,buffer2_not_recd=
0,buffer3_not_recd=0,buffer4_not_recd=0,buffer5_not_recd=0,buffer6_not_recd=0,buffer7_not_recd=0,mack,maxalarms=100,STANDALONE=0,pn_connected=0,ACKNOWLEDGE=0,ACKNOWLEDGE1=0,NETWORK=0,USER="",PW="",ACCESS="RX",UID=0,RESTORE=0,socket,pubnub,channelName="TAGDB",channelNameScada="TAGDB_scada",TAGDB,dbobj,ARSTATUS="",buffer="";ttime=mack=0;if(void 0==TAGSFILE||""==TAGSFILE)TAGSFILE=DEFAULT_TAGSFILE;console.log("HOSTNAME,PROJECTNAME,PORT,TAGSFILE=",HOSTNAME,PROJECTNAME,PORT,TAGSFILE);
if(1==REMOTE){var timeouterror=function(){0==ACKNOWLEDGE&&alert("No response from PubNub server!(Check Internet)")};pubnub=new PubNub({publish_key:pub_key,subscribe_key:sub_key,ssl:!0});pubnub.subscribe({channels:[channelName,"response",channelNameScada]});pubnub.addListener({status:function(a){"PNConnectedCategory"===a.category?(console.log("pubnub connected event triggered"),0==UID&&(UID=PubNub.generateUUID(),pn_connected=1,pubnub.publish({channel:"commands_channel",message:UID+"~ACKNOWLEDGE"}))):
"PNNetworkUpCategory"===a.category?NETWORK=1:"PNNetworkDownCategory"===a.category&&(NETWORK=0)},message:function(a){message_handler(a)},presence:function(a){}});setTimeout(timeouterror,3E4)}else if(0==REMOTE)mm={channel:"",message:""},console.log("IO socket UID",UID),0==UID&&(socket=io("/ar")),console.log("IO socket opened"),socket.on("newclientconnect",function(a){console.log("new client connected =",a.description);UID=socket.id;console.log("emitting ACKNOWLEDGE");socket.emit("commands_channel",
UID+"~ACKNOWLEDGE");console.log("new client opened",UID)}),socket.on("Connecting ",function(){console.log(">>>>Connecting event")}),socket.on("Disconnect ",function(){console.log(">>>>Disconnect event")}),socket.on("Connect_failed ",function(){console.log(">>>>connect failed event")}),socket.on("Error ",function(){console.log(">>>>ERROR event")}),socket.on("Reconnect ",function(){console.log(">>>>Reconnect event")}),socket.on("Reconnecting ",function(){console.log(">>>>Reconnecting event")}),socket.on("Reconnect_failed ",
function(){console.log(">>>>Reconnect_failed event")}),socket.on("response",function(a){mm.channel="response";mm.message=a;message_handler(mm)}),socket.on(channelName,function(a){mm.channel=channelName;mm.message=a;message_handler(mm)}),socket.on(channelNameScada,function(a){mm.channel=channelNameScada;mm.message=a;message_handler(mm)});else if(2==REMOTE){mm={channel:"",message:""};ACKNOWLEDGE=1;scenename=channelNameScada=channelName+"_scada";if(void 0==cycle_time||""==cycle_time)cycle_time="5";ctime=
parseInt(cycle_time);USER=DEFAULTUSER="ADMIN";NJPORT=0;NETWORK=1;if(0==STANDALONE){var com1,com2,com3;com2=getAjaxData('{"names":["command"],"values":["GETTAGS:'+TAGSFILE+'"]}');com2.then(function(a){dbobj=JSON.parse('{"TAGDB":'+a+"}");TAGS='{"TAGS":"ARSTATUS~';for(a=0;a<dbobj.TAGDB.length;a++)TAGS+=dbobj.TAGDB[a].name+"~";TAGS+='"}';getAjaxData('{"names":["command"],"values":["SCAN:'+TAGSFILE+'"]}').then(function(a){mm.channel=channelNameScada;a=JSON.parse(a);mm.message=a.value;message_handler(mm)});
setInterval(function(){(1==LICENSE||60>ttime)&&getAjaxData('{"names":["command"],"values":["SCAN:'+TAGSFILE+'"]}').then(function(a){mm.channel=channelNameScada;a=JSON.parse(a);mm.message=a.value;message_handler(mm);ttime+=ctime})},1E3*ctime)})}else{var tim=0;setInterval(function(){mm.channel=channelNameScada;var a=tim+",0~",b=Date(),c=b.substring(4,15),b=b.substring(16,24);mm.message="ALL!admin,RX,0,"+c+",0,        ,"+b+",0~"+a+a+a+a+a+a+a+a+a+a+a+a+a+"false,0~16,0~false,0~";tim+=1;100<tim&&(tim=
0);message_handler(mm)},5E3)}}function getAjaxData(a){return new Promise(function(b,c){var d=new XMLHttpRequest;d.onreadystatechange=function(){4==this.readyState&&200==this.status&&b(this.responseText)};d.open("POST","http://"+HOSTNAME+":"+PORT+"/main/system/webdev/"+PROJECTNAME+"/postjson",!0);d.setRequestHeader("Content-type","application/json");d.send(a)})}function timeout(a){return new Promise(function(b,c){setTimeout(function(){return b(1)},a)})}
function message_handler(a){if(a.channel!=channelName)if("response"==a.channel){if(a=a.message.split("~"),a[0]==UID||"ALL"==a[0])"ACKNOWLEDGE"==a[1]?(ACKNOWLEDGE=1,STANDALONE=1==parseInt(a[2])?0:1,channelName=a[3],scenename=channelNameScada=channelName+"_scada",cycle_time=a[4],DEFAULTUSER=a[5],HOSTNAME=a[6],NJPORT=a[7],NETWORK=1,getTags(channelNameScada)):"LOGIN"==a[1]?"SUCCESS"==a[2]?(USER=a[3],ACCESS=a[4],"undefined"!=typeof Storage&&(sessionStorage.defaultuser=USER,sessionStorage.access=ACCESS,
console.log("User,Access=",USER,ACCESS),console.log("Login success")),"admin"!=USER&&(EDIT=0)):(alert("Login Failure, try again"),login()):"TAGS"==a[1]?(TAGS=a[2],TAGS=TAGS.replace(/\^/gi,"~"),1==REMOTE?pubnub.publish({channel:"commands_channel",message:UID+"~SCAN~"+channelNameScada}):socket.emit("commands_channel",UID+"~SCAN~"+channelNameScada),console.log("SCAN Command sent",channelNameScada),"undefined"!=typeof Storage&&sessionStorage.defaultuser?(console.log("default user taken as=",sessionStorage.defaultuser),
USER=sessionStorage.defaultuser,ACCESS=sessionStorage.access,EDIT="admin"!=USER?0:1):login()):"PUT"==a[1]&&a[0]==UID?(buffer1=a[2],buffer1_not_recd=0):"PUT1"==a[1]&&a[0]==UID?(buffer2=a[2],buffer2_not_recd=0):"INC"==a[1]&&a[0]==UID?(buffer3=a[2],buffer3_not_recd=0):"DEC"==a[1]&&a[0]==UID?(buffer4=a[2],buffer4_not_recd=0):"PUTGET"==a[1]&&a[0]==UID?(console.log("PUTGET "+a[0],a[1],a[2]),buffer6=a[2],buffer6_not_recd=0,buffer6.startsWith("false")&&console.log("error PUTGET="+buffer6)):"TOGGLE"==a[1]&&
a[0]==UID&&(buffer7=a[2],buffer7_not_recd=0)}else if(a.channel==channelNameScada){if(ACKNOWLEDGE1=1,a.message.startsWith("ALL")||a.message.startsWith(UID)){var b=a.message.indexOf("!");curtime=1==REMOTE?a.timetoken:0;buffer=a.message.slice(b);setval()}}else console.log("Channel=",a.channel)}function gethost(a){""==a||void 0==a?window.open("http://"+HOSTNAME+":"+PORT+"/main/system/webdev/"+PROJECTNAME+"/ARS/systemlist.html","_self"):window.open(a,"_blank")}
function login(){for(var a=0;1>a&&(USER=prompt("Enter user Name",DEFAULTUSER),null==USER););for(a=0;1>a&&(PW=prompt("Enter password",""),null==PW););1==REMOTE?pubnub.publish({channel:"commands_channel",message:UID+"~LOGIN~"+USER+"~"+PW}):socket.emit("commands_channel",UID+"~LOGIN~"+USER+"~"+PW)}function getTags(a){1==REMOTE?pubnub.publish({channel:"commands_channel",message:UID+"~TAGS~"+a}):0==REMOTE&&(socket.emit("commands_channel",UID+"~TAGS~"+a),console.log("GetTags executed"))}
function refresh(a){1==REMOTE?pubnub.publish({channel:"commands_channel",message:UID+"~REFRESH~"+a}):socket.emit("commands_channel",UID+"~REFRESH~"+a)}function putval(a){buffer1="";buffer1_not_recd=1;console.log("PUT:"+a);1==REMOTE?pubnub.publish({channel:"commands_channel",message:UID+"~PUT~"+a+"~"+scenename}):socket.emit("commands_channel",UID+"~PUT~"+a+"~"+scenename)}
function putval1(a){buffer2="";buffer2_not_recd=1;console.log("PUT1:"+a);1==REMOTE?pubnub.publish({channel:"commands_channel",message:UID+"~PUT1~"+a+"~"+scenename}):socket.emit("commands_channel",UID+"~PUT1~"+a+"~"+scenename)}function incval(a){buffer3="";buffer3_not_recd=1;console.log("INC:"+a);1==REMOTE?pubnub.publish({channel:"commands_channel",message:UID+"~INC~"+a+"~"+scenename}):socket.emit("commands_channel",UID+"~INC~"+a+"~"+scenename)}
function decval(a){buffer4="";buffer4_not_recd=1;console.log("DEC:"+a);1==REMOTE?pubnub.publish({channel:"commands_channel",message:UID+"~DEC~"+a+"~"+scenename}):socket.emit("commands_channel",UID+"~DEC~"+a+"~"+scenename)}function putgetval(a){buffer6="";buffer6_not_recd=1;console.log("PUTGET:"+a);1==REMOTE?pubnub.publish({channel:"commands_channel",message:UID+"~PUTGET~"+a+"~"+scenename}):socket.emit("commands_channel",UID+"~PUTGET~"+a+"~"+scenename)}
function toggle(a){buffer7="";buffer7_not_recd=1;console.log("TOGGLE:"+a);1==REMOTE?pubnub.publish({channel:"commands_channel",message:UID+"~TOGGLE~"+a+"~"+scenename}):socket.emit("commands_channel",UID+"~TOGGLE~"+a+"~"+scenename)}
function somefunction31(a,b){var c,d,e,f,g,h;if(0==b.length)return a;e=""!=TAGS&&"XX"!=ACCESS||"ARSTATUS"==a?TAGS.indexOf(a):-1;if(0>e)return 0;for(c=d=0;c<e;c++)"~"==TAGS.charAt(c)&&d++;e=b.length;g=0;h=e;for(c=f=0;c<e;c++)if("~"==b.charAt(c))if(f++,f>d){h=c;break}else g=c+1;return b.substring(g,h).split(",")[0]}
function setval(){if(0!=buffer.length){var a,b;a=buffer.split("~");if(!(0>=a.lenght))for(b=a[0].split("!"),ARSTATUS=b[1],b=1;b<a.length-1;b++){var c,d=b-1;c=a[b].split(",");dbobj.TAGDB[d].val=c[0];dbobj.TAGDB[d].state="0";dbobj.TAGDB[d].con="";dbobj.TAGDB[d].lim="";dbobj.TAGDB[d].label="";1<c.length&&(dbobj.TAGDB[d].state=c[1],c=parseInt(c[1]),0<dbobj.TAGDB[d].conditions.length&&(dbobj.TAGDB[d].con=dbobj.TAGDB[d].conditions[c].cond,dbobj.TAGDB[d].lim=dbobj.TAGDB[d].conditions[c].lim,dbobj.TAGDB[d].label=
dbobj.TAGDB[d].conditions[c].label))}}}function getattr(a){a=searchTag(a);return 0>a?",,,0,0":dbobj.TAGDB[a].type+","+dbobj.TAGDB[a].def+","+dbobj.TAGDB[a].unit+","+dbobj.TAGDB[a].width+","+dbobj.TAGDB[a].deci}function searchTag(a){for(var b=0;b<dbobj.TAGDB.length;b++)if(dbobj.TAGDB[b].name==a)return b;return-1}
function somefunction(a){if("ARSTATUS"==a)return ARSTATUS;a=searchTag(a);return 0>a?"":"="!=dbobj.TAGDB[a].con?dbobj.TAGDB[a].val+","+dbobj.TAGDB[a].state+", "+dbobj.TAGDB[a].con+" "+dbobj.TAGDB[a].lim+" "+dbobj.TAGDB[a].label:dbobj.TAGDB[a].val+","+dbobj.TAGDB[a].state+", "+dbobj.TAGDB[a].label}function somefunction1(a){if("ARSTATUS"==a)return ARSTATUS;a=searchTag(a);return 0>a?"":dbobj.TAGDB[a].val+","+dbobj.TAGDB[a].state+", "+dbobj.TAGDB[a].label}
function somefunction3(a){if("ARSTATUS"==a)return ARSTATUS;a=searchTag(a);return 0>a?"":dbobj.TAGDB[a].val}function getAlarms(){var a="";if(0<dbobj.TAGDB.length)for(i=0;i<dbobj.TAGDB.length;i++)0<dbobj.TAGDB[i].state&&(a+=dbobj.TAGDB[i].name+";");return a}function getSceneName(a){if(0<dbobj.TAGDB.length)for(i=0;i<dbobj.TAGDB.length;i++)if(dbobj.TAGDB[i].name==a)return dbobj.TAGDB[i].links[0].scene+";"+dbobj.TAGDB[i].links[0].hs;return";"}function getbuf1(){return buffer1.trim()}
function getbuf2(){return buffer2.trim()}function getbuf3(){return buffer3.trim()}function getbuf4(){return buffer4.trim()}function getbuf5(){return buffer5.trim()}function getbuf6(){return buffer6.trim()}function getbuf7(){return buffer7.trim()}function getcycletime(){var a=parseInt(cycle_time);if(5>a||isNaN(a))cycle_time="5";return cycle_time}function krpano_image_is_ready(a){console.log("Krpano image is ready called "+scenename);buffer="";mack=0}
function macknowledge(){return mack=0==mack?1:0}function getaccess(){return ACCESS}function getuser(){return USER}function refreshScreen(){refresh(scenename)}function mack_status(){return mack}function write_permission(){return!0};
